/**
 * Unity Combat System Template
 * Health and damage system for characters
 */

export const UNITY_COMBAT_TEMPLATE = `using UnityEngine;
using UnityEngine.Events;

/// <summary>
/// Combat System with Health and Damage
/// Handles health management, damage dealing, and death
/// Generated by ORBITAI Game Mechanics Service
/// </summary>
public class CombatSystem : MonoBehaviour
{
    [Header("Health Settings")]
    [Tooltip("Maximum health points")]
    public float maxHealth = {{MAX_HEALTH}}f;
    
    [Tooltip("Starting health (defaults to max if 0)")]
    public float startingHealth = 0f;
    
    [Tooltip("Is this character invincible?")]
    public bool isInvincible = false;
    
    [Header("Combat Settings")]
    [Tooltip("Base damage dealt by attacks")]
    public float baseDamage = {{BASE_DAMAGE}}f;
    
    [Tooltip("Attack range for melee")]
    public float attackRange = {{ATTACK_RANGE}}f;
    
    [Tooltip("Layers that can be damaged")]
    public LayerMask damageableLayers;
    
    [Header("Events")]
    public UnityEvent<float> OnDamageTaken;
    public UnityEvent<float> OnHealthChanged;
    public UnityEvent OnDeath;
    
    // Current health
    private float currentHealth;
    
    void Start()
    {
        currentHealth = startingHealth > 0 ? startingHealth : maxHealth;
    }
    
    /// <summary>
    /// Take damage from an attack
    /// </summary>
    public void TakeDamage(float damage)
    {
        if (isInvincible || currentHealth <= 0)
            return;
        
        currentHealth -= damage;
        currentHealth = Mathf.Max(0, currentHealth);
        
        OnDamageTaken?.Invoke(damage);
        OnHealthChanged?.Invoke(currentHealth);
        
        Debug.Log($"{gameObject.name} took {damage} damage. Health: {currentHealth}/{maxHealth}");
        
        if (currentHealth <= 0)
        {
            Die();
        }
    }
    
    /// <summary>
    /// Heal the character
    /// </summary>
    public void Heal(float amount)
    {
        if (currentHealth <= 0)
            return;
        
        currentHealth += amount;
        currentHealth = Mathf.Min(currentHealth, maxHealth);
        
        OnHealthChanged?.Invoke(currentHealth);
        
        Debug.Log($"{gameObject.name} healed {amount}. Health: {currentHealth}/{maxHealth}");
    }
    
    /// <summary>
    /// Perform a melee attack
    /// </summary>
    public void Attack()
    {
        // Find all colliders in attack range
        Collider2D[] hits = Physics2D.OverlapCircleAll(
            transform.position,
            attackRange,
            damageableLayers
        );
        
        foreach (Collider2D hit in hits)
        {
            // Don't damage self
            if (hit.gameObject == gameObject)
                continue;
            
            // Try to damage the hit object
            CombatSystem targetCombat = hit.GetComponent<CombatSystem>();
            if (targetCombat != null)
            {
                targetCombat.TakeDamage(baseDamage);
                Debug.Log($"{gameObject.name} attacked {hit.gameObject.name} for {baseDamage} damage");
            }
        }
    }
    
    /// <summary>
    /// Handle death
    /// </summary>
    private void Die()
    {
        Debug.Log($"{gameObject.name} has died!");
        OnDeath?.Invoke();
        
        // Disable this GameObject (or destroy it)
        gameObject.SetActive(false);
        // Destroy(gameObject); // Uncomment to destroy instead
    }
    
    /// <summary>
    /// Get current health percentage
    /// </summary>
    public float GetHealthPercentage()
    {
        return currentHealth / maxHealth;
    }
    
    /// <summary>
    /// Check if character is alive
    /// </summary>
    public bool IsAlive()
    {
        return currentHealth > 0;
    }
    
    // Visualize attack range in editor
    void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, attackRange);
    }
}
`;

export const UNITY_COMBAT_CONFIG = {
    id: 'unity-combat-system',
    name: 'Combat System (Unity)',
    category: 'combat' as const,
    engine: 'unity' as const,
    language: 'csharp' as const,
    variables: [
        {
            name: 'MAX_HEALTH',
            type: 'number' as const,
            default: 100,
            description: 'Maximum health points',
            min: 10,
            max: 1000
        },
        {
            name: 'BASE_DAMAGE',
            type: 'number' as const,
            default: 10,
            description: 'Damage dealt per attack',
            min: 1,
            max: 100
        },
        {
            name: 'ATTACK_RANGE',
            type: 'number' as const,
            default: 1.5,
            description: 'Attack range for melee attacks',
            min: 0.5,
            max: 10
        }
    ],
    dependencies: [],
    instructions: `# Unity Combat System - Setup Instructions

## Prerequisites
- Unity 2D project
- Characters with Rigidbody2D and Collider2D

## Installation Steps

1. **Attach to Character**
   - Select Player or Enemy GameObject
   - Add Component → CombatSystem

2. **Configure Settings**
   - Max Health: 100 (player), 50 (enemies)
   - Base Damage: 10 (player), 5 (enemies)
   - Attack Range: 1.5 for melee

3. **Set Damageable Layers**
   - Create layers: "Player", "Enemy"
   - For Player: Set Damageable Layers to "Enemy"
   - For Enemy: Set Damageable Layers to "Player"

4. **Trigger Attacks** (add to your input script):
\`\`\`csharp
if (Input.GetKeyDown(KeyCode.F)) {
    GetComponent<CombatSystem>().Attack();
}
\`\`\`

5. **Hook Up Events** (optional, in Inspector):
   - OnDamageTaken: Play damage animation/sound
   - OnHealthChanged: Update health bar UI
   - OnDeath: Play death animation

## Usage Examples

**Take Damage:**
\`\`\`csharp
combatSystem.TakeDamage(20f);
\`\`\`

**Heal:**
\`\`\`csharp
combatSystem.Heal(30f);
\`\`\`

**Check Health:**
\`\`\`csharp
float healthPercent = combatSystem.GetHealthPercentage();
bool alive = combatSystem.IsAlive();
\`\`\`

## Customization Tips
- Lower max health for weaker enemies
- Increase attack range for weapons
- Set isInvincible temporarily for power-ups
- Use OnDeath event to drop items/XP

## Troubleshooting
- **No damage dealt**: Check damageable layers are set correctly
- **Self-damage**: Ensure character layer is not in damageable layers
- **Attack not triggered**: Call Attack() method from input handler
`
};
