/**
 * Unity 2D Platformer Movement Template
 * Complete player movement script for 2D platformer games
 */

export const UNITY_2D_MOVEMENT_TEMPLATE = `using UnityEngine;

/// <summary>
/// 2D Platformer Player Controller
/// Handles movement, jumping, and basic physics
/// Generated by ORBITAI Game Mechanics Service
/// </summary>
public class PlayerController : MonoBehaviour
{
    [Header("Movement Settings")]
    [Tooltip("Horizontal movement speed")]
    public float moveSpeed = {{MOVE_SPEED}}f;
    
    [Tooltip("Jump force applied when jumping")]
    public float jumpForce = {{JUMP_FORCE}}f;
    
    [Tooltip("Maximum number of jumps allowed (1 = single jump, 2 = double jump)")]
    public int maxJumps = {{MAX_JUMPS}};
    
    [Header("Ground Detection")]
    [Tooltip("Layer mask for ground detection")]
    public LayerMask groundLayer;
    
    [Tooltip("Offset for ground check position")]
    public Vector2 groundCheckOffset = new Vector2(0f, -0.5f);
    
    [Tooltip("Size of ground check box")]
    public Vector2 groundCheckSize = new Vector2(0.8f, 0.1f);
    
    // Private variables
    private Rigidbody2D rb;
    private int jumpsRemaining;
    private bool isGrounded;
    private float moveInput;
    
    void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        if (rb == null)
        {
            Debug.LogError("PlayerController requires a Rigidbody2D component!");
        }
        jumpsRemaining = maxJumps;
    }
    
    void Update()
    {
        // Get input
        moveInput = Input.GetAxisRaw("Horizontal");
        
        // Check if grounded
        CheckGrounded();
        
        // Reset jumps when grounded
        if (isGrounded)
        {
            jumpsRemaining = maxJumps;
        }
        
        // Jump input
        if (Input.GetKeyDown(KeyCode.Space) && jumpsRemaining > 0)
        {
            Jump();
        }
        
        // Flip sprite based on movement direction
        if (moveInput > 0)
        {
            transform.localScale = new Vector3(1f, 1f, 1f);
        }
        else if (moveInput < 0)
        {
            transform.localScale = new Vector3(-1f, 1f, 1f);
        }
    }
    
    void FixedUpdate()
    {
        // Apply horizontal movement
        rb.velocity = new Vector2(moveInput * moveSpeed, rb.velocity.y);
    }
    
    private void Jump()
    {
        // Reset vertical velocity for consistent jumps
        rb.velocity = new Vector2(rb.velocity.x, 0f);
        
        // Apply jump force
        rb.AddForce(Vector2.up * jumpForce, ForceMode2D.Impulse);
        
        // Decrease remaining jumps
        jumpsRemaining--;
    }
    
    private void CheckGrounded()
    {
        // Use box cast for ground detection
        Vector2 checkPosition = (Vector2)transform.position + groundCheckOffset;
        isGrounded = Physics2D.OverlapBox(checkPosition, groundCheckSize, 0f, groundLayer);
    }
    
    // Visualize ground check in editor
    void OnDrawGizmos()
    {
        Gizmos.color = isGrounded ? Color.green : Color.red;
        Vector2 checkPosition = (Vector2)transform.position + groundCheckOffset;
        Gizmos.DrawWireCube(checkPosition, groundCheckSize);
    }
}
`;

export const UNITY_2D_MOVEMENT_CONFIG = {
    id: 'unity-2d-movement',
    name: '2D Platformer Movement',
    category: 'movement' as const,
    engine: 'unity' as const,
    language: 'csharp' as const,
    variables: [
        {
            name: 'MOVE_SPEED',
            type: 'number' as const,
            default: 5.0,
            description: 'Horizontal movement speed',
            min: 1.0,
            max: 20.0
        },
        {
            name: 'JUMP_FORCE',
            type: 'number' as const,
            default: 10.0,
            description: 'Upward force applied when jumping',
            min: 5.0,
            max: 30.0
        },
        {
            name: 'MAX_JUMPS',
            type: 'number' as const,
            default: 1,
            description: 'Maximum number of jumps (1 = single, 2 = double jump)',
            min: 1,
            max: 3
        }
    ],
    dependencies: [],
    instructions: `# Unity 2D Platformer Movement - Setup Instructions

## Prerequisites
- Unity 2D project
- Player GameObject with Rigidbody2D (set to Dynamic, Freeze Rotation Z = true)
- Ground objects with appropriate layer (e.g., "Ground")

## Installation Steps

1. **Attach Script**
   - Select your Player GameObject
   - Add Component → Scripts → PlayerController

2. **Configure Rigidbody2D**
   - Body Type: Dynamic
   - Gravity Scale: 3 (adjust for feel)
   - Constraints → Freeze Rotation Z: ✓ (checked)

3. **Set Ground Layer**
   - Create a Layer called "Ground" (if not exists)
   - Assign ground GameObjects to "Ground" layer
   - In PlayerController inspector, set Ground Layer to "Ground"

4. **Adjust Settings** (Optional)
   - Move Speed: 5-7 for normal speed
   - Jump Force: 10-15 for normal jump height
   - Max Jumps: 1 for single jump, 2 for double jump

5. **Test**
   - Press Play
   - Use WASD or Arrow Keys to move
   - Press Space to jump

## Customization Tips
- Lower gravity scale (e.g., 2) for floatier jumps
- Higher move speed (e.g., 8-10) for faster gameplay
- Adjust ground check offset if player doesn't detect ground properly

## Troubleshooting
- **Player falls through ground**: Check ground layer is correctly set
- **Jumps feel weak**: Increase jump force or decrease gravity scale
- **Movement too fast/slow**: Adjust move speed value
- **Ground detection issues**: Visualize ground check box in Scene view (green = grounded)
`
};
