import mongoose, { Schema, Document } from 'mongoose';

export interface IKnowledgeBase extends Document {
  id: string;
  name: string;
  description: string;
  category: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'best-practices' | 'troubleshooting' | 'general';
  
  // Content
  content: string; // Main content (Markdown)
  structuredContent?: {
    sections?: Array<{
      title: string;
      content: string;
      order: number;
    }>;
    faq?: Array<{
      question: string;
      answer: string;
    }>;
    references?: Array<{
      title: string;
      url?: string;
      type: 'documentation' | 'article' | 'standard' | 'tool' | 'other';
    }>;
  };
  
  // Organization
  parentId?: string; // For hierarchical organization
  children?: string[]; // Child knowledge base items
  level: number; // Depth in hierarchy (0 = root)
  
  // Metadata
  version: number;
  versionHistory: Array<{
    version: number;
    content: string;
    changedBy: string;
    changeDate: Date;
    changeReason: string;
    validityPeriod?: {
      start: Date;
      end?: Date;
    };
  }>;
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  priority: 'low' | 'medium' | 'high' | 'critical';
  deprecatedAt?: Date;
  deprecatedReason?: string;
  
  // Applicability
  applicableTo: {
    agentRoles?: string[];
    projectTypes?: string[];
    methodologies?: string[];
    industries?: string[];
    standards?: string[];
  };
  
  // Usage and effectiveness
  usage: {
    views: number;
    lastViewed?: Date;
    timesReferenced: number;
    lastReferenced?: Date;
    helpfulCount: number;
    notHelpfulCount: number;
    feedback?: Array<{
      helpful: boolean;
      comment?: string;
      userId?: string;
      timestamp: Date;
    }>;
  };
  
  // Improvement tracking
  improvementHistory: Array<{
    version: number;
    changedBy: string;
    changeDate: Date;
    changeReason: string;
    changes: string;
  }>;
  
  // Tags and search
  tags: string[];
  keywords: string[];
  
  // Related items
  relatedItems?: Array<{
    type: 'knowledge-base' | 'process-improvement' | 'guideline' | 'template';
    id: string;
    title: string;
    relationship: 'related' | 'prerequisite' | 'follow-up' | 'alternative';
  }>;
  
  // Quality metrics
  quality: {
    completeness: number; // 0-100
    accuracy: number; // 0-100
    clarity: number; // 0-100
    usefulness: number; // 0-100 (calculated from usage)
    lastReviewed?: Date;
    reviewedBy?: string;
  };
  
  // Auto-generated from agent learning
  autoGenerated: boolean;
  source?: {
    type: 'agent-learning' | 'user-created' | 'imported' | 'system-generated' | 'aggregated';
    agentRole?: string;
    taskId?: string;
    projectId?: string;
    aggregatedFrom?: string[]; // IDs of items this was aggregated from
  };
  // Privacy and sharing
  sharing: {
    scope: 'project' | 'user' | 'global';
    sharedProjects?: string[];
    qualityGate: {
      passed: boolean;
      score: number; // 0-100
      checkedAt?: Date;
    };
  };
  
  // Approval workflow
  approval?: {
    status: 'pending' | 'approved' | 'rejected';
    approvedBy?: string;
    approvedAt?: Date;
    rejectedReason?: string;
    requiresApproval: boolean;
  };
  
  // Embedding for semantic search
  embedding?: number[];
  
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
  updatedBy: string;
}

const knowledgeBaseSchema = new Schema<IKnowledgeBase>(
  {
    id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true
    },
    name: {
      type: String,
      required: true,
      trim: true,
      index: true
    },
    description: {
      type: String,
      required: true
    },
    category: {
      type: String,
      enum: ['process', 'technical', 'quality', 'security', 'compliance', 'best-practices', 'troubleshooting', 'general'],
      required: true,
      index: true
    },
    content: {
      type: String,
      required: true
    },
    structuredContent: {
      sections: [{
        title: String,
        content: String,
        order: Number
      }],
      faq: [{
        question: String,
        answer: String
      }],
      references: [{
        title: String,
        url: String,
        type: {
          type: String,
          enum: ['documentation', 'article', 'standard', 'tool', 'other']
        }
      }]
    },
    parentId: {
      type: String,
      index: true,
      sparse: true
    },
    children: [String],
    level: {
      type: Number,
      default: 0,
      index: true
    },
    version: {
      type: Number,
      default: 1
    },
    versionHistory: [{
      version: Number,
      content: String,
      changedBy: String,
      changeDate: { type: Date, default: Date.now },
      changeReason: String,
      validityPeriod: {
        start: Date,
        end: Date
      }
    }],
    status: {
      type: String,
      enum: ['draft', 'active', 'deprecated', 'archived'],
      default: 'draft',
      index: true
    },
    deprecatedAt: Date,
    deprecatedReason: String,
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'critical'],
      default: 'medium',
      index: true
    },
    applicableTo: {
      agentRoles: [String],
      projectTypes: [String],
      methodologies: [String],
      industries: [String],
      standards: [String]
    },
    usage: {
      views: { type: Number, default: 0 },
      lastViewed: Date,
      timesReferenced: { type: Number, default: 0 },
      lastReferenced: Date,
      helpfulCount: { type: Number, default: 0 },
      notHelpfulCount: { type: Number, default: 0 },
      feedback: [{
        helpful: Boolean,
        comment: String,
        userId: String,
        timestamp: { type: Date, default: Date.now }
      }]
    },
    improvementHistory: [{
      version: Number,
      changedBy: String,
      changeDate: { type: Date, default: Date.now },
      changeReason: String,
      changes: String
    }],
    tags: [String],
    keywords: [String],
    relatedItems: [{
      type: String,
      id: String,
      title: String,
      relationship: {
        type: String,
        enum: ['related', 'prerequisite', 'follow-up', 'alternative']
      }
    }],
    quality: {
      completeness: { type: Number, min: 0, max: 100, default: 0 },
      accuracy: { type: Number, min: 0, max: 100, default: 0 },
      clarity: { type: Number, min: 0, max: 100, default: 0 },
      usefulness: { type: Number, min: 0, max: 100, default: 0 },
      lastReviewed: Date,
      reviewedBy: String
    },
    autoGenerated: {
      type: Boolean,
      default: false
    },
    source: {
      type: {
        type: String,
        enum: ['agent-learning', 'user-created', 'imported', 'system-generated', 'aggregated']
      },
      agentRole: String,
      taskId: String,
      projectId: String,
      aggregatedFrom: [String]
    },
    sharing: {
      scope: {
        type: String,
        enum: ['project', 'user', 'global'],
        default: 'project'
      },
      sharedProjects: [String],
      qualityGate: {
        passed: { type: Boolean, default: false },
        score: { type: Number, min: 0, max: 100, default: 0 },
        checkedAt: Date
      }
    },
    approval: {
      status: {
        type: String,
        enum: ['pending', 'approved', 'rejected'],
        default: 'pending'
      },
      approvedBy: String,
      approvedAt: Date,
      rejectedReason: String,
      requiresApproval: { type: Boolean, default: false }
    },
    embedding: [Number],
    createdBy: {
      type: String,
      required: true
    },
    updatedBy: {
      type: String,
      required: true
    }
  },
  {
    timestamps: true
  }
);

// Indexes
knowledgeBaseSchema.index({ name: 'text', description: 'text', content: 'text', tags: 'text', keywords: 'text' });
knowledgeBaseSchema.index({ category: 1, status: 1, priority: 1 });
knowledgeBaseSchema.index({ 'applicableTo.agentRoles': 1 });
knowledgeBaseSchema.index({ parentId: 1, level: 1 });
knowledgeBaseSchema.index({ createdAt: -1 });
knowledgeBaseSchema.index({ 'usage.views': -1 });

export const KnowledgeBase = mongoose.model<IKnowledgeBase>('KnowledgeBase', knowledgeBaseSchema);
















