import mongoose, { Schema, Document } from 'mongoose';

export interface IProcessImprovement extends Document {
  id: string;
  title: string;
  description: string;
  category: 'guideline' | 'template' | 'best-practice' | 'workflow' | 'checklist' | 'standard';
  type: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'general';
  
  // Content
  content: string; // Markdown or structured content
  structuredContent?: {
    sections?: Array<{
      title: string;
      content: string;
      order: number;
    }>;
    steps?: Array<{
      step: number;
      title: string;
      description: string;
      checklist?: string[];
    }>;
    examples?: Array<{
      title: string;
      description: string;
      code?: string;
      output?: string;
    }>;
  };
  
  // Metadata
  version: number;
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  priority: 'low' | 'medium' | 'high' | 'critical';
  
  // Applicability
  applicableTo: {
    agentRoles?: string[]; // Which agents this applies to
    projectTypes?: string[]; // Which project types
    methodologies?: string[]; // Which SDLC methodologies
    industries?: string[]; // Which industries
    standards?: string[]; // Related quality standards
  };
  
  // Usage tracking
  usage: {
    timesUsed: number;
    lastUsed?: Date;
    successRate?: number; // 0-100
    feedback?: Array<{
      rating: number; // 1-5
      comment?: string;
      userId?: string;
      timestamp: Date;
    }>;
  };
  
  // Improvement tracking
  improvementHistory: Array<{
    version: number;
    changedBy: string; // User ID or 'system'
    changeDate: Date;
    changeReason: string;
    changes: string; // Description of changes
  }>;
  
  // Tags and search
  tags: string[];
  keywords: string[];
  
  // References
  relatedImprovements?: string[]; // IDs of related improvements
  referencedBy?: Array<{
    type: 'guideline' | 'template' | 'knowledge-base';
    id: string;
    title: string;
  }>;
  
  // Approval workflow
  approval?: {
    status: 'pending' | 'approved' | 'rejected' | 'agent-assessing' | 'agent-refining';
    approvedBy?: string; // User ID or 'agent'
    approvedAt?: Date;
    rejectedReason?: string;
    requiresApproval: boolean;
    // Agent assessment fields
    agentAssessment?: {
      decision: 'approve' | 'work-on' | 'reject';
      reasoning: string;
      confidence: number;
      assessedAt: Date;
      refinedAt?: Date;
      rejectionReason?: string; // Required if decision is 'reject'
    };
  };
  
  // Quality metrics
  quality: {
    completeness: number; // 0-100
    clarity: number; // 0-100
    usefulness: number; // 0-100 (calculated from usage)
    lastReviewed?: Date;
    reviewedBy?: string;
  };
  
  // Auto-generated from agent learning
  autoGenerated: boolean;
  source?: {
    type: 'agent-learning' | 'user-created' | 'imported' | 'system-generated';
    agentRole?: string;
    taskId?: string;
    projectId?: string;
  };
  
  // Knowledge base integration
  knowledgeBaseRefs: Array<{
    kbId: string;
    kbName: string;
    relevance: number; // 0-100
  }>;
  
  createdAt: Date;
  updatedAt: Date;
  createdBy: string; // User ID
  updatedBy: string; // User ID
}

const processImprovementSchema = new Schema<IProcessImprovement>(
  {
    id: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true
    },
    title: {
      type: String,
      required: true,
      trim: true,
      index: true
    },
    description: {
      type: String,
      required: true
    },
    category: {
      type: String,
      enum: ['guideline', 'template', 'best-practice', 'workflow', 'checklist', 'standard'],
      required: true,
      index: true
    },
    type: {
      type: String,
      enum: ['process', 'technical', 'quality', 'security', 'compliance', 'general'],
      required: true,
      index: true
    },
    content: {
      type: String,
      required: true
    },
    structuredContent: {
      sections: [{
        title: String,
        content: String,
        order: Number
      }],
      steps: [{
        step: Number,
        title: String,
        description: String,
        checklist: [String]
      }],
      examples: [{
        title: String,
        description: String,
        code: String,
        output: String
      }]
    },
    version: {
      type: Number,
      default: 1
    },
    status: {
      type: String,
      enum: ['draft', 'active', 'deprecated', 'archived'],
      default: 'draft',
      index: true
    },
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'critical'],
      default: 'medium',
      index: true
    },
    applicableTo: {
      agentRoles: [String],
      projectTypes: [String],
      methodologies: [String],
      industries: [String],
      standards: [String]
    },
    usage: {
      timesUsed: { type: Number, default: 0 },
      lastUsed: Date,
      successRate: { type: Number, min: 0, max: 100 },
      feedback: [{
        rating: { type: Number, min: 1, max: 5 },
        comment: String,
        userId: String,
        timestamp: { type: Date, default: Date.now }
      }]
    },
    improvementHistory: [{
      version: Number,
      changedBy: String,
      changeDate: { type: Date, default: Date.now },
      changeReason: String,
      changes: String
    }],
    tags: [String],
    keywords: [String],
    relatedImprovements: [String],
    referencedBy: [{
      type: String,
      id: String,
      title: String
    }],
    approval: {
      status: {
        type: String,
        enum: ['pending', 'approved', 'rejected', 'agent-assessing', 'agent-refining'],
        default: 'pending'
      },
      approvedBy: String,
      approvedAt: Date,
      rejectedReason: String,
      requiresApproval: { type: Boolean, default: false },
      agentAssessment: {
        decision: { type: String, enum: ['approve', 'work-on', 'reject'] },
        reasoning: String,
        confidence: { type: Number, min: 0, max: 100 },
        assessedAt: Date,
        refinedAt: Date,
        rejectionReason: String
      }
    },
    quality: {
      completeness: { type: Number, min: 0, max: 100, default: 0 },
      clarity: { type: Number, min: 0, max: 100, default: 0 },
      usefulness: { type: Number, min: 0, max: 100, default: 0 },
      lastReviewed: Date,
      reviewedBy: String
    },
    autoGenerated: {
      type: Boolean,
      default: false
    },
    source: {
      type: {
        type: String,
        enum: ['agent-learning', 'user-created', 'imported', 'system-generated']
      },
      agentRole: String,
      taskId: String,
      projectId: String
    },
    knowledgeBaseRefs: [{
      kbId: String,
      kbName: String,
      relevance: { type: Number, min: 0, max: 100 }
    }],
    createdBy: {
      type: String,
      required: true
    },
    updatedBy: {
      type: String,
      required: true
    }
  },
  {
    timestamps: true
  }
);

// Indexes for efficient searching
processImprovementSchema.index({ title: 'text', description: 'text', tags: 'text', keywords: 'text' });
processImprovementSchema.index({ category: 1, type: 1, status: 1 });
processImprovementSchema.index({ 'applicableTo.agentRoles': 1 });
processImprovementSchema.index({ 'applicableTo.methodologies': 1 });
processImprovementSchema.index({ status: 1, priority: 1 });
processImprovementSchema.index({ createdAt: -1 });
processImprovementSchema.index({ 'usage.timesUsed': -1 });

export const ProcessImprovement = mongoose.model<IProcessImprovement>('ProcessImprovement', processImprovementSchema);




