/**
 * Phaser 3 Platformer Movement Template
 * JavaScript player controller for web-based platformer games
 */

export const PHASER_2D_MOVEMENT_TEMPLATE = `/**
 * 2D Platformer Player Controller for Phaser 3
 * Handles movement, jumping, and basic physics
 * Generated by ORBITAI Game Mechanics Service
 */

class PlayerController {
    constructor(scene, x, y) {
        this.scene = scene;
        
        // Movement settings
        this.moveSpeed = {{MOVE_SPEED}};
        this.jumpForce = {{JUMP_FORCE}};
        this.maxJumps = {{MAX_JUMPS}};
        
        // Create player sprite
        this.sprite = scene.physics.add.sprite(x, y, 'player');
        this.sprite.setCollideWorldBounds(true);
        
        // Internal state
        this.jumpsRemaining = this.maxJumps;
        this.isGrounded = false;
        
        // Input keys
        this.cursors = scene.input.keyboard.createCursorKeys();
        this.wKey = scene.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.W);
        this.aKey = scene.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.A);
        this.sKey = scene.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.S);
        this.dKey = scene.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.D);
        this.spaceKey = scene.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.SPACE);
    }
    
    update() {
        // Check if grounded
        this.isGrounded = this.sprite.body.touching.down;
        
        // Reset jumps when grounded
        if (this.isGrounded) {
            this.jumpsRemaining = this.maxJumps;
        }
        
        // Horizontal movement
        if (this.cursors.left.isDown || this.aKey.isDown) {
            this.sprite.setVelocityX(-this.moveSpeed);
            this.sprite.setFlipX(true);
        } else if (this.cursors.right.isDown || this.dKey.isDown) {
            this.sprite.setVelocityX(this.moveSpeed);
            this.sprite.setFlipX(false);
        } else {
            this.sprite.setVelocityX(0);
        }
        
        // Jump
        if (Phaser.Input.Keyboard.JustDown(this.cursors.up) || 
            Phaser.Input.Keyboard.JustDown(this.spaceKey) || 
            Phaser.Input.Keyboard.JustDown(this.wKey)) {
            if (this.jumpsRemaining > 0) {
                this.jump();
            }
        }
    }
    
    jump() {
        this.sprite.setVelocityY(-this.jumpForce);
        this.jumpsRemaining--;
    }
    
    getSprite() {
        return this.sprite;
    }
}

// Export for use in game scene
export default PlayerController;
`;

export const PHASER_2D_MOVEMENT_CONFIG = {
    id: 'phaser-2d-movement',
    name: '2D Platformer Movement (Phaser 3)',
    category: 'movement' as const,
    engine: 'phaser' as const,
    language: 'javascript' as const,
    variables: [
        {
            name: 'MOVE_SPEED',
            type: 'number' as const,
            default: 160,
            description: 'Horizontal movement speed (pixels per second)',
            min: 80,
            max: 400
        },
        {
            name: 'JUMP_FORCE',
            type: 'number' as const,
            default: 330,
            description: 'Upward velocity applied when jumping',
            min: 200,
            max: 600
        },
        {
            name: 'MAX_JUMPS',
            type: 'number' as const,
            default: 1,
            description: 'Maximum number of jumps (1 = single, 2 = double jump)',
            min: 1,
            max: 3
        }
    ],
    dependencies: ['phaser@^3.60.0'],
    instructions: `# Phaser 3 Platformer Movement - Setup Instructions

## Prerequisites
- Node.js project with Phaser 3 installed
- Basic Phaser game scene setup
- Player sprite asset loaded

## Installation Steps

1. **Install Phaser** (if not already):
\`\`\`bash
npm install phaser@^3.60.0
\`\`\`

2. **Save PlayerController**:
   - Create \`/src/PlayerController.js\`
   - Paste the generated code

3. **Use in Game Scene**:
\`\`\`javascript
import PlayerController from './PlayerController';

class GameScene extends Phaser.Scene {
    create() {
        // Create platforms
        this.platforms = this.physics.add.staticGroup();
        this.platforms.create(400, 568, 'ground');
        
        // Create player
        this.player = new PlayerController(this, 100, 450);
        
        // Enable collision
        this.physics.add.collider(
            this.player.getSprite(), 
            this.platforms
        );
    }
    
    update() {
        this.player.update();
    }
}
\`\`\`

4. **Load Assets** (in preload()):
\`\`\`javascript
preload() {
    this.load.image('player', 'assets/player.png');
    this.load.image('ground', 'assets/platform.png');
}
\`\`\`

5. **Test**:
   - Run with \`npm start\`
   - Use Arrow Keys, WASD, or Space to move and jump

## Customization Tips
- Adjust moveSpeed for faster/slower movement
- Increase jumpForce for higher jumps
- Set maxJumps to 2 for double jump ability
- Modify sprite.setGravityY() for different gravity feel

## Troubleshooting
- **Player falls through ground**: Ensure collision is set up
- **Can't jump**: Check if platforms have static physics body
- **Movement too fast**: Lower moveSpeed value
- **Sprite not showing**: Verify asset is loaded in preload()
`
};
