/**
 * Process Improvement API Service
 * Frontend service for managing process improvements, guidelines, templates, and knowledge base
 */

import { apiRequest } from './adminApi';

const API_BASE_URL = import.meta.env.VITE_API_URL || '';

export interface ProcessImprovement {
  id: string;
  title: string;
  description: string;
  category: 'guideline' | 'template' | 'best-practice' | 'workflow' | 'checklist' | 'standard';
  type: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'general';
  content: string;
  structuredContent?: {
    sections?: Array<{ title: string; content: string; order: number }>;
    steps?: Array<{ step: number; title: string; description: string; checklist?: string[] }>;
    examples?: Array<{ title: string; description: string; code?: string; output?: string }>;
  };
  version: number;
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  priority: 'low' | 'medium' | 'high' | 'critical';
  applicableTo: {
    agentRoles?: string[];
    projectTypes?: string[];
    methodologies?: string[];
    industries?: string[];
    standards?: string[];
  };
  usage: {
    timesUsed: number;
    lastUsed?: string;
    successRate?: number;
    feedback?: Array<{ rating: number; comment?: string; userId?: string; timestamp: string }>;
  };
  improvementHistory: Array<{
    version: number;
    changedBy: string;
    changeDate: string;
    changeReason: string;
    changes: string;
  }>;
  tags: string[];
  keywords: string[];
  quality: {
    completeness: number;
    clarity: number;
    usefulness: number;
    lastReviewed?: string;
    reviewedBy?: string;
  };
  autoGenerated: boolean;
  source?: {
    type: 'agent-learning' | 'user-created' | 'imported' | 'system-generated';
    agentRole?: string;
    taskId?: string;
    projectId?: string;
  };
  approval?: {
    status: 'pending' | 'approved' | 'rejected' | 'agent-assessing' | 'agent-refining';
    approvedBy?: string;
    approvedAt?: string;
    rejectedReason?: string;
    requiresApproval: boolean;
    agentAssessment?: {
      decision: 'approve' | 'work-on';
      reasoning: string;
      confidence: number;
      assessedAt: string;
      refinedAt?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeBaseEntry {
  id: string;
  name: string;
  description: string;
  category: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'best-practices' | 'troubleshooting' | 'general';
  content: string;
  structuredContent?: {
    sections?: Array<{ title: string; content: string; order: number }>;
    faq?: Array<{ question: string; answer: string }>;
    references?: Array<{ title: string; url?: string; type: string }>;
  };
  version: number;
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  priority: 'low' | 'medium' | 'high' | 'critical';
  applicableTo: {
    agentRoles?: string[];
    projectTypes?: string[];
    methodologies?: string[];
    industries?: string[];
    standards?: string[];
  };
  usage: {
    views: number;
    lastViewed?: string;
    timesReferenced: number;
    helpfulCount: number;
    notHelpfulCount: number;
  };
  tags: string[];
  keywords: string[];
  quality: {
    completeness: number;
    accuracy: number;
    clarity: number;
    usefulness: number;
  };
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ProcessImprovementListResponse {
  improvements: ProcessImprovement[];
  total: number;
  limit: number;
  offset: number;
}

export interface KnowledgeBaseListResponse {
  entries: KnowledgeBaseEntry[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * Get all process improvements with filters
 */
export async function getProcessImprovements(
  token: string,
  filters?: {
    search?: string;
    category?: string;
    type?: string;
    status?: string;
    agentRole?: string;
    methodology?: string;
    tags?: string[];
    limit?: number;
    offset?: number;
  }
): Promise<ProcessImprovementListResponse> {
  const params = new URLSearchParams();
  if (filters?.search) params.append('search', filters.search);
  if (filters?.category) params.append('category', filters.category);
  if (filters?.type) params.append('type', filters.type);
  if (filters?.status) params.append('status', filters.status);
  if (filters?.agentRole) params.append('agentRole', filters.agentRole);
  if (filters?.methodology) params.append('methodology', filters.methodology);
  if (filters?.tags) {
    filters.tags.forEach(tag => params.append('tags', tag));
  }
  if (filters?.limit) params.append('limit', filters.limit.toString());
  if (filters?.offset) params.append('offset', filters.offset.toString());

  const queryString = params.toString();
  const endpoint = `/api/admin/process-improvements${queryString ? `?${queryString}` : ''}`;

  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovementListResponse;
  }>(endpoint, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch process improvements');
  }

  return response.data;
}

/**
 * Get specific process improvement
 */
export async function getProcessImprovement(
  token: string,
  id: string
): Promise<ProcessImprovement> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement;
  }>(`/api/admin/process-improvements/${id}`, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch process improvement');
  }

  return response.data;
}

/**
 * Create process improvement
 */
export async function createProcessImprovement(
  token: string,
  data: Partial<ProcessImprovement>
): Promise<ProcessImprovement> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement;
  }>('/api/admin/process-improvements', {
    method: 'POST',
    body: JSON.stringify(data),
  }, token);

  if (!response.success) {
    throw new Error('Failed to create process improvement');
  }

  return response.data;
}

/**
 * Update process improvement
 */
export async function updateProcessImprovement(
  token: string,
  id: string,
  updates: Partial<ProcessImprovement>,
  changeReason?: string
): Promise<ProcessImprovement> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement;
  }>(`/api/admin/process-improvements/${id}`, {
    method: 'PUT',
    body: JSON.stringify({ ...updates, changeReason }),
  }, token);

  if (!response.success) {
    throw new Error('Failed to update process improvement');
  }

  return response.data;
}

/**
 * Delete process improvement (archive)
 */
export async function deleteProcessImprovement(
  token: string,
  id: string
): Promise<void> {
  const response = await apiRequest<{
    success: boolean;
    message: string;
  }>(`/api/admin/process-improvements/${id}`, {
    method: 'DELETE',
  }, token);

  if (!response.success) {
    throw new Error('Failed to delete process improvement');
  }
}

/**
 * Approve process improvement
 */
export async function approveProcessImprovement(
  token: string,
  id: string
): Promise<ProcessImprovement> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement;
  }>(`/api/admin/process-improvements/${id}/approve`, {
    method: 'POST',
  }, token);

  if (!response.success) {
    throw new Error('Failed to approve process improvement');
  }

  return response.data;
}

/**
 * Reject process improvement
 */
export async function rejectProcessImprovement(
  token: string,
  id: string,
  reason?: string
): Promise<ProcessImprovement> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement;
  }>(`/api/admin/process-improvements/${id}/reject`, {
    method: 'POST',
    body: JSON.stringify({ reason }),
  }, token);

  if (!response.success) {
    throw new Error('Failed to reject process improvement');
  }

  return response.data;
}

/**
 * Get knowledge base entries
 */
export async function getKnowledgeBaseEntries(
  token: string,
  filters?: {
    search?: string;
    category?: string;
    status?: string;
    agentRole?: string;
    parentId?: string;
    limit?: number;
    offset?: number;
  }
): Promise<KnowledgeBaseListResponse> {
  const params = new URLSearchParams();
  if (filters?.search) params.append('search', filters.search);
  if (filters?.category) params.append('category', filters.category);
  if (filters?.status) params.append('status', filters.status);
  if (filters?.agentRole) params.append('agentRole', filters.agentRole);
  if (filters?.parentId !== undefined) params.append('parentId', filters.parentId);
  if (filters?.limit) params.append('limit', filters.limit.toString());
  if (filters?.offset) params.append('offset', filters.offset.toString());

  const queryString = params.toString();
  const endpoint = `/api/admin/process-improvements/knowledge-base${queryString ? `?${queryString}` : ''}`;

  const response = await apiRequest<{
    success: boolean;
    data: KnowledgeBaseListResponse;
  }>(endpoint, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch knowledge base entries');
  }

  return response.data;
}

/**
 * Get specific knowledge base entry
 */
export async function getKnowledgeBaseEntry(
  token: string,
  id: string
): Promise<KnowledgeBaseEntry> {
  const response = await apiRequest<{
    success: boolean;
    data: KnowledgeBaseEntry;
  }>(`/api/admin/process-improvements/knowledge-base/${id}`, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch knowledge base entry');
  }

  return response.data;
}

/**
 * Create knowledge base entry
 */
export async function createKnowledgeBaseEntry(
  token: string,
  data: Partial<KnowledgeBaseEntry>
): Promise<KnowledgeBaseEntry> {
  const response = await apiRequest<{
    success: boolean;
    data: KnowledgeBaseEntry;
  }>('/api/admin/process-improvements/knowledge-base', {
    method: 'POST',
    body: JSON.stringify(data),
  }, token);

  if (!response.success) {
    throw new Error('Failed to create knowledge base entry');
  }

  return response.data;
}

/**
 * Update knowledge base entry
 */
export async function updateKnowledgeBaseEntry(
  token: string,
  id: string,
  updates: Partial<KnowledgeBaseEntry>,
  changeReason?: string
): Promise<KnowledgeBaseEntry> {
  const response = await apiRequest<{
    success: boolean;
    data: KnowledgeBaseEntry;
  }>(`/api/admin/process-improvements/knowledge-base/${id}`, {
    method: 'PUT',
    body: JSON.stringify({ ...updates, changeReason }),
  }, token);

  if (!response.success) {
    throw new Error('Failed to update knowledge base entry');
  }

  return response.data;
}

/**
 * Delete knowledge base entry (archive)
 */
export async function deleteKnowledgeBaseEntry(
  token: string,
  id: string
): Promise<void> {
  const response = await apiRequest<{
    success: boolean;
    message: string;
  }>(`/api/admin/process-improvements/knowledge-base/${id}`, {
    method: 'DELETE',
  }, token);

  if (!response.success) {
    throw new Error('Failed to delete knowledge base entry');
  }
}

/**
 * Get improvements for specific agent
 */
export async function getImprovementsForAgent(
  token: string,
  agentRole: string
): Promise<ProcessImprovement[]> {
  const response = await apiRequest<{
    success: boolean;
    data: ProcessImprovement[];
  }>(`/api/admin/process-improvements/agent/${agentRole}`, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch improvements for agent');
  }

  return response.data;
}

/**
 * Trigger agent assessment for all pending process improvements
 */
export async function assessAllPendingImprovements(
  token: string
): Promise<{ success: boolean; message: string }> {
  const response = await apiRequest<{
    success: boolean;
    message: string;
  }>('/api/admin/process-improvements/assess-pending', {
    method: 'POST',
  }, token);

  if (!response.success) {
    throw new Error('Failed to trigger assessment');
  }

  return response;
}

/**
 * Trigger agent assessment for a specific process improvement
 */
export async function assessProcessImprovement(
  token: string,
  id: string
): Promise<{ success: boolean; message: string; data: ProcessImprovement }> {
  const response = await apiRequest<{
    success: boolean;
    message: string;
    data: ProcessImprovement;
  }>(`/api/admin/process-improvements/${id}/assess`, {
    method: 'POST',
  }, token);

  if (!response.success) {
    throw new Error('Failed to trigger assessment');
  }

  return response;
}

/**
 * Get stuck improvements that are in agent-assessing or agent-refining status
 */
export async function getStuckImprovements(
  token: string,
  timeoutMinutes: number = 5
): Promise<{ count: number; improvements: ProcessImprovement[]; cutoffTime: string }> {
  const response = await apiRequest<{
    success: boolean;
    data: { count: number; improvements: ProcessImprovement[]; cutoffTime: string };
  }>(`/api/admin/process-improvements/stuck?timeoutMinutes=${timeoutMinutes}`, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to get stuck improvements');
  }

  return response.data;
}

/**
 * Clean up stuck improvements
 */
export async function cleanupStuckImprovements(
  token: string,
  timeoutMinutes: number = 5
): Promise<{ cleaned: number; errors: number }> {
  const response = await apiRequest<{
    success: boolean;
    message: string;
    data: { cleaned: number; errors: number };
  }>('/api/admin/process-improvements/cleanup-stuck', {
    method: 'POST',
    body: JSON.stringify({ timeoutMinutes }),
  }, token);

  if (!response.success) {
    throw new Error('Failed to cleanup stuck improvements');
  }

  return response.data;
}




