/**
 * Process Analytics API Service
 * Frontend service for process analytics
 */

import { apiRequest } from './adminApi';

export interface ProcessAnalytics {
  overview: {
    totalImprovements: number;
    activeImprovements: number;
    totalKnowledgeBase: number;
    activeKnowledgeBase: number;
    autoGenerated: number;
    pendingApproval: number;
  };
  usage: {
    mostUsed: Array<{ id: string; title: string; timesUsed: number }>;
    leastUsed: Array<{ id: string; title: string; timesUsed: number }>;
    averageUsage: number;
    totalUsage: number;
  };
  quality: {
    averageCompleteness: number;
    averageClarity: number;
    averageUsefulness: number;
    highQuality: number;
    lowQuality: number;
  };
  categories: Array<{
    category: string;
    count: number;
    averageSuccessRate: number;
  }>;
  trends: {
    created: Array<{ date: string; count: number }>;
    used: Array<{ date: string; count: number }>;
  };
  recommendations: string[];
}

export interface ROIData {
  timesUsed: number;
  averageSuccessRate: number;
  estimatedTimeSaved: number;
  estimatedValue: number;
}

/**
 * Get comprehensive analytics
 */
export async function getProcessAnalytics(
  token: string,
  startDate?: string,
  endDate?: string
): Promise<ProcessAnalytics> {
  const params = new URLSearchParams();
  if (startDate) params.append('startDate', startDate);
  if (endDate) params.append('endDate', endDate);

  const queryString = params.toString();
  const endpoint = `/api/admin/process-analytics${queryString ? `?${queryString}` : ''}`;

  const response = await apiRequest<{
    success: boolean;
    data: ProcessAnalytics;
  }>(endpoint, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to fetch process analytics');
  }

  return response.data;
}

/**
 * Calculate ROI for an improvement
 */
export async function calculateROI(
  token: string,
  improvementId: string
): Promise<ROIData> {
  const response = await apiRequest<{
    success: boolean;
    data: ROIData;
  }>(`/api/admin/process-analytics/roi/${improvementId}`, {
    method: 'GET',
  }, token);

  if (!response.success) {
    throw new Error('Failed to calculate ROI');
  }

  return response.data;
}
















