/**
 * Process Improvement Service
 * Manages process improvements, guidelines, templates, and knowledge base
 */

import { ProcessImprovement, IProcessImprovement } from '../models/ProcessImprovement.model.js';
import { KnowledgeBase, IKnowledgeBase } from '../models/KnowledgeBase.model.js';
import { AgentKnowledge } from '../models/AgentKnowledge.model.js';
import { ActivityEvent } from '../models/ActivityEvent.model.js';
import { logger } from '../utils/logger.js';
import crypto from 'crypto';
import { neo4jService } from './neo4j.service.js';
import { processImprovementAgentAssessment } from './processImprovementAgentAssessment.service.js';

export interface ProcessImprovementInput {
  title: string;
  description: string;
  category: 'guideline' | 'template' | 'best-practice' | 'workflow' | 'checklist' | 'standard';
  type: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'general';
  content: string;
  structuredContent?: IProcessImprovement['structuredContent'];
  applicableTo?: IProcessImprovement['applicableTo'];
  tags?: string[];
  keywords?: string[];
  priority?: 'low' | 'medium' | 'high' | 'critical';
  status?: 'draft' | 'active' | 'deprecated' | 'archived';
  requiresApproval?: boolean;
}

export interface KnowledgeBaseInput {
  name: string;
  description: string;
  category: IKnowledgeBase['category'];
  content: string;
  structuredContent?: IKnowledgeBase['structuredContent'];
  applicableTo?: IKnowledgeBase['applicableTo'];
  tags?: string[];
  keywords?: string[];
  priority?: 'low' | 'medium' | 'high' | 'critical';
  status?: 'draft' | 'active' | 'deprecated' | 'archived';
  parentId?: string;
  requiresApproval?: boolean;
}

class ProcessImprovementService {
  /**
   * Create a new process improvement
   */
  async createImprovement(
    input: ProcessImprovementInput,
    userId: string
  ): Promise<IProcessImprovement> {
    const id = `pi-${crypto.randomUUID()}`;
    
    const improvement = await ProcessImprovement.create({
      id,
      ...input,
      version: 1,
      status: input.status || 'draft',
      priority: input.priority || 'medium',
      tags: input.tags || [],
      keywords: input.keywords || [],
      applicableTo: input.applicableTo || {},
      usage: {
        timesUsed: 0,
        successRate: 0
      },
      improvementHistory: [],
      quality: {
        completeness: this.calculateCompleteness(input),
        clarity: 0,
        usefulness: 0
      },
      autoGenerated: false,
      approval: {
        status: input.requiresApproval ? 'agent-assessing' : 'approved',
        requiresApproval: input.requiresApproval || false
      },
      knowledgeBaseRefs: [],
      createdBy: userId,
      updatedBy: userId
    });

    logger.info(`Created process improvement: ${id} - ${input.title}`);

    // If requires approval, trigger agent assessment asynchronously
    if (input.requiresApproval) {
      // Don't await - let it run in background
      this.triggerAgentAssessment(improvement.id).catch((error: any) => {
        logger.error(`Failed to trigger agent assessment for ${improvement.id}:`, error);
      });
    }

    // ENHANCEMENT: Create Neo4j node for knowledge graph
    try {
      if (neo4jService.isAvailable()) {
        await neo4jService.createNode(
          ['ProcessImprovement'],
          {
            id: improvement.id,
            title: improvement.title,
            category: improvement.category,
            type: improvement.type,
            status: improvement.status,
            priority: improvement.priority
          }
        );
        logger.debug(`Created Neo4j node for improvement: ${id}`);
      }
    } catch (neo4jError: any) {
      logger.warn('Failed to create Neo4j node (non-critical):', neo4jError.message);
    }

    return improvement;
  }

  /**
   * Update a process improvement
   */
  async updateImprovement(
    id: string,
    updates: Partial<ProcessImprovementInput>,
    userId: string,
    changeReason?: string
  ): Promise<IProcessImprovement> {
    const improvement = await ProcessImprovement.findOne({ id });
    
    if (!improvement) {
      throw new Error(`Process improvement not found: ${id}`);
    }

    // Track changes in history
    const oldVersion = improvement.version;
    const changes: string[] = [];
    
    if (updates.title && updates.title !== improvement.title) {
      changes.push(`Title: "${improvement.title}" → "${updates.title}"`);
    }
    if (updates.content && updates.content !== improvement.content) {
      changes.push('Content updated');
    }
    if (updates.status && updates.status !== improvement.status) {
      changes.push(`Status: ${improvement.status} → ${updates.status}`);
    }

    // Update fields
    Object.assign(improvement, updates);
    improvement.version = oldVersion + 1;
    improvement.updatedBy = userId;

    // Add to improvement history
    if (changes.length > 0) {
      improvement.improvementHistory.push({
        version: improvement.version,
        changedBy: userId,
        changeDate: new Date(),
        changeReason: changeReason || 'Updated by admin',
        changes: changes.join('; ')
      });
    }

    // Recalculate quality if content changed
    if (updates.content) {
      improvement.quality.completeness = this.calculateCompleteness({
        ...improvement.toObject(),
        ...updates
      } as ProcessImprovementInput);
    }

    await improvement.save();
    logger.info(`Updated process improvement: ${id} to version ${improvement.version}`);
    
    return improvement;
  }

  /**
   * Create knowledge base entry
   */
  async createKnowledgeBase(
    input: KnowledgeBaseInput,
    userId: string
  ): Promise<IKnowledgeBase> {
    const id = `kb-${crypto.randomUUID()}`;
    
    // Determine level if parentId provided
    let level = 0;
    if (input.parentId) {
      const parent = await KnowledgeBase.findOne({ id: input.parentId });
      if (parent) {
        level = parent.level + 1;
      }
    }

    const knowledgeBase = await KnowledgeBase.create({
      id,
      ...input,
      level,
      version: 1,
      status: input.status || 'draft',
      priority: input.priority || 'medium',
      tags: input.tags || [],
      keywords: input.keywords || [],
      applicableTo: input.applicableTo || {},
      usage: {
        views: 0,
        timesReferenced: 0,
        helpfulCount: 0,
        notHelpfulCount: 0
      },
      improvementHistory: [],
      quality: {
        completeness: this.calculateKBCompleteness(input),
        accuracy: 0,
        clarity: 0,
        usefulness: 0
      },
      autoGenerated: false,
      approval: {
        status: input.requiresApproval ? 'pending' : 'approved',
        requiresApproval: input.requiresApproval || false
      },
      createdBy: userId,
      updatedBy: userId
    });

    // Update parent's children array
    if (input.parentId) {
      await KnowledgeBase.updateOne(
        { id: input.parentId },
        { $addToSet: { children: id } }
      );
    }

    logger.info(`Created knowledge base entry: ${id} - ${input.name}`);
    return knowledgeBase;
  }

  /**
   * Auto-generate improvement from agent learning
   */
  async generateFromAgentLearning(
    agentRole: string,
    taskData: {
      taskTitle: string;
      taskDescription: string;
      success: boolean;
      evaluation?: { score: number; criteria: string[] };
      skillsUsed?: string[];
      domainsUsed?: string[];
    }
  ): Promise<IProcessImprovement | null> {
    try {
      const agentKnowledge = await AgentKnowledge.findOne({ agentRole });
      
      if (!agentKnowledge || !taskData.success) {
        return null; // Only generate from successful tasks
      }

      // Check if similar improvement already exists
      const existing = await ProcessImprovement.findOne({
        'source.agentRole': agentRole,
        'source.taskId': taskData.taskTitle,
        autoGenerated: true
      });

      if (existing) {
        return null; // Already exists
      }

      // Generate improvement based on successful task
      const improvement = await this.createImprovement(
        {
          title: `Best Practice: ${taskData.taskTitle}`,
          description: `Auto-generated from successful ${agentRole} task execution`,
          category: 'best-practice',
          type: 'process',
          content: this.generateContentFromTask(taskData, agentKnowledge),
          applicableTo: {
            agentRoles: [agentRole]
          },
          tags: ['auto-generated', 'agent-learning', agentRole.toLowerCase()],
          keywords: taskData.skillsUsed || [],
          priority: taskData.evaluation?.score && taskData.evaluation.score >= 90 ? 'high' : 'medium',
          status: 'draft', // Requires review
          requiresApproval: true
        },
        'system'
      );

      // Mark as auto-generated
      improvement.autoGenerated = true;
      improvement.source = {
        type: 'agent-learning',
        agentRole,
        taskId: taskData.taskTitle
      };
      await improvement.save();

      logger.info(`Auto-generated process improvement from agent learning: ${improvement.id}`);
      return improvement;
    } catch (error: any) {
      logger.error('Failed to generate improvement from agent learning:', error);
      return null;
    }
  }

  /**
   * Search improvements
   */
  async searchImprovements(query: {
    search?: string;
    category?: string;
    type?: string;
    status?: string;
    agentRole?: string;
    methodology?: string;
    tags?: string[];
    limit?: number;
    offset?: number;
  }): Promise<{ improvements: IProcessImprovement[]; total: number }> {
    const filter: any = {};

    if (query.search) {
      filter.$text = { $search: query.search };
    }
    if (query.category) {
      filter.category = query.category;
    }
    if (query.type) {
      filter.type = query.type;
    }
    if (query.status) {
      filter.status = query.status;
    }
    if (query.agentRole) {
      filter['applicableTo.agentRoles'] = query.agentRole;
    }
    if (query.methodology) {
      filter['applicableTo.methodologies'] = query.methodology;
    }
    if (query.tags && query.tags.length > 0) {
      filter.tags = { $in: query.tags };
    }

    const limit = query.limit || 20;
    const offset = query.offset || 0;

    const [improvements, total] = await Promise.all([
      ProcessImprovement.find(filter)
        .sort({ priority: -1, 'usage.timesUsed': -1, createdAt: -1 })
        .limit(limit)
        .skip(offset)
        .lean(),
      ProcessImprovement.countDocuments(filter)
    ]);

    return { improvements, total };
  }

  /**
   * Get improvements for agent
   */
  async getImprovementsForAgent(agentRole: string): Promise<IProcessImprovement[]> {
    return ProcessImprovement.find({
      status: 'active',
      $or: [
        { 'applicableTo.agentRoles': { $in: [agentRole] } },
        { 'applicableTo.agentRoles': { $size: 0 } } // Global improvements
      ]
    })
      .sort({ priority: -1, 'usage.timesUsed': -1 })
      .lean();
  }

  /**
   * Record usage of improvement
   */
  async recordUsage(id: string, success: boolean): Promise<void> {
    const improvement = await ProcessImprovement.findOne({ id });
    if (!improvement) return;

    improvement.usage.timesUsed += 1;
    improvement.usage.lastUsed = new Date();

    // Update success rate
    const currentSuccessRate = improvement.usage.successRate || 100;
    const successCount = Math.floor((currentSuccessRate / 100) * (improvement.usage.timesUsed - 1));
    const newSuccessRate = success
      ? ((successCount + 1) / improvement.usage.timesUsed) * 100
      : (successCount / improvement.usage.timesUsed) * 100;
    improvement.usage.successRate = Math.round(newSuccessRate * 100) / 100;

    // Update usefulness based on success rate
    improvement.quality.usefulness = improvement.usage.successRate;

    await improvement.save();
  }

  // Helper methods
  private calculateCompleteness(input: ProcessImprovementInput): number {
    let score = 0;
    if (input.title) score += 10;
    if (input.description) score += 10;
    if (input.content) score += 30;
    if (input.structuredContent?.sections && input.structuredContent.sections.length > 0) score += 20;
    if (input.structuredContent?.steps && input.structuredContent.steps.length > 0) score += 20;
    if (input.structuredContent?.examples && input.structuredContent.examples.length > 0) score += 10;
    return Math.min(100, score);
  }

  private calculateKBCompleteness(input: KnowledgeBaseInput): number {
    let score = 0;
    if (input.name) score += 10;
    if (input.description) score += 10;
    if (input.content) score += 40;
    if (input.structuredContent?.sections && input.structuredContent.sections.length > 0) score += 20;
    if (input.structuredContent?.faq && input.structuredContent.faq.length > 0) score += 10;
    if (input.structuredContent?.references && input.structuredContent.references.length > 0) score += 10;
    return Math.min(100, score);
  }

  private generateContentFromTask(
    taskData: any,
    agentKnowledge: any
  ): string {
    const skills = taskData.skillsUsed?.join(', ') || 'various skills';
    const domains = taskData.domainsUsed?.join(', ') || 'multiple domains';
    const score = taskData.evaluation?.score || 0;

    return `# ${taskData.taskTitle}

## Overview
This best practice was automatically generated from a successful task execution by the ${agentKnowledge.agentRole}.

**Task**: ${taskData.taskDescription}

**Success Rate**: ${score}%

## Skills Applied
${skills}

## Knowledge Domains
${domains}

## Key Learnings
${taskData.evaluation?.criteria?.map((c: string) => `- ${c}`).join('\n') || 'No specific criteria documented'}

## Recommendations
This approach has proven successful and should be considered for similar tasks in the future.

---
*Auto-generated from agent learning system*
`;
  }

  /**
   * Assess all pending process improvements that need agent assessment
   * Can be called manually or on service startup
   * IMPORTANT: Only assesses 'pending' status - excludes 'agent-assessing' and 'agent-refining' to prevent loops
   */
  async assessAllPendingImprovements(): Promise<{ assessed: number; errors: number }> {
    let assessed = 0;
    let errors = 0;

    try {
      // First, cleanup any stuck improvements before assessing new ones
      const cleanupResult = await this.cleanupStuckImprovements(5); // 5 minute timeout
      if (cleanupResult.cleaned > 0) {
        logger.info(`Cleaned up ${cleanupResult.cleaned} stuck improvements before assessment`);
      }

      // Find only improvements that are truly pending (not already being assessed/refined)
      // Exclude 'agent-assessing' and 'agent-refining' to prevent infinite loops
      const pendingImprovements = await ProcessImprovement.find({
        'approval.requiresApproval': true,
        'approval.status': 'pending' // Only assess truly pending improvements
      });

      logger.info(`Found ${pendingImprovements.length} pending improvements to assess`);

      // Update old 'pending' status to 'agent-assessing' for consistency
      const oldPending = pendingImprovements.filter(p => p.approval?.status === 'pending');
      if (oldPending.length > 0) {
        await ProcessImprovement.updateMany(
          { 
            id: { $in: oldPending.map(p => p.id) },
            'approval.status': 'pending'
          },
          { 
            $set: { 'approval.status': 'agent-assessing' }
          }
        );
        logger.info(`Updated ${oldPending.length} improvements from 'pending' to 'agent-assessing'`);
      }

      // Assess each improvement (run in parallel but limit concurrency)
      const batchSize = 5; // Process 5 at a time to avoid overwhelming the LLM
      for (let i = 0; i < pendingImprovements.length; i += batchSize) {
        const batch = pendingImprovements.slice(i, i + batchSize);
        await Promise.allSettled(
          batch.map(improvement => 
            this.triggerAgentAssessment(improvement.id)
              .then(() => {
                assessed++;
                logger.info(`Assessed improvement: ${improvement.id}`);
              })
              .catch((error: any) => {
                errors++;
                logger.error(`Failed to assess improvement ${improvement.id}:`, error);
              })
          )
        );
        
        // Small delay between batches to avoid rate limiting
        if (i + batchSize < pendingImprovements.length) {
          await new Promise(resolve => setTimeout(resolve, 2000));
        }
      }

      logger.info(`Assessment complete: ${assessed} assessed, ${errors} errors`);
      return { assessed, errors };
    } catch (error: any) {
      logger.error('Failed to assess pending improvements:', error);
      return { assessed, errors };
    }
  }

  /**
   * Trigger agent assessment for a specific process improvement
   * Can be called manually for existing improvements
   */
  async triggerAgentAssessmentForImprovement(improvementId: string): Promise<void> {
    return this.triggerAgentAssessment(improvementId);
  }

  /**
   * Trigger agent assessment for a process improvement
   * Runs asynchronously in the background
   */
  private async triggerAgentAssessment(improvementId: string): Promise<void> {
    const startTime = Date.now();
    
    try {
      const improvement = await ProcessImprovement.findOne({ id: improvementId });
      if (!improvement || !improvement.approval?.requiresApproval) {
        return;
      }

      // Check if already being assessed/refined (prevent duplicate assessments)
      if (improvement.approval.status === 'agent-assessing' || improvement.approval.status === 'agent-refining') {
        logger.warn(`Improvement ${improvementId} is already being assessed/refined, skipping duplicate assessment`);
        return;
      }

      // Update status to agent-assessing
      improvement.approval.status = 'agent-assessing';
      await improvement.save();

      logger.info(`Agent assessment started for improvement: ${improvementId}`);
      
      // Log activity event for assessment start
      await ActivityEvent.create({
        type: 'agent_assessment_started',
        entityType: 'process_improvement',
        entityId: improvementId,
        details: {
          title: improvement.title,
          category: improvement.category,
          improvementType: improvement.type,
          agentRole: 'QA/Audit Agent',
          action: 'assessment_started'
        },
        timestamp: new Date()
      });

      // Get agent assessment
      const assessment = await processImprovementAgentAssessment.assessImprovement(improvement);

      // Update improvement with assessment
      improvement.approval.agentAssessment = {
        decision: assessment.decision,
        reasoning: assessment.reasoning,
        confidence: assessment.confidence,
        assessedAt: new Date(),
        ...(assessment.decision === 'reject' && assessment.rejectionReason && {
          rejectionReason: assessment.rejectionReason
        })
      };

      if (assessment.decision === 'approve') {
        // Agent approves - mark as approved
        improvement.approval.status = 'approved';
        improvement.approval.approvedBy = 'agent';
        improvement.approval.approvedAt = new Date();
        if (improvement.status === 'draft') {
          improvement.status = 'active';
        }
        logger.info(`Agent approved improvement: ${improvementId}`);
        
        // Log activity event for assessment completion
        await ActivityEvent.create({
          type: 'agent_assessment_completed',
          entityType: 'process_improvement',
          entityId: improvementId,
          details: {
            title: improvement.title,
            decision: 'approve',
            confidence: assessment.confidence,
            reasoning: assessment.reasoning,
            durationMs: Date.now() - startTime,
            agentRole: 'QA/Audit Agent'
          },
          timestamp: new Date()
        });
      } else if (assessment.decision === 'reject') {
        // Agent rejects - mark as rejected
        improvement.approval.status = 'rejected';
        improvement.approval.rejectedReason = assessment.rejectionReason || assessment.reasoning || 'Rejected by agent - content does not meet quality standards';
        improvement.approval.approvedBy = 'agent';
        improvement.approval.approvedAt = new Date();
        logger.info(`Agent rejected improvement: ${improvementId} - Reason: ${improvement.approval.rejectedReason}`);
        
        // Log activity event for rejection
        await ActivityEvent.create({
          type: 'agent_assessment_completed',
          entityType: 'process_improvement',
          entityId: improvementId,
          details: {
            title: improvement.title,
            decision: 'reject',
            confidence: assessment.confidence,
            reasoning: assessment.reasoning,
            rejectionReason: improvement.approval.rejectedReason,
            durationMs: Date.now() - startTime,
            agentRole: 'QA/Audit Agent'
          },
          timestamp: new Date()
        });
      } else {
        // Agent wants to work on it - refine the improvement
        improvement.approval.status = 'agent-refining';
        await improvement.save();

        logger.info(`Agent refining improvement: ${improvementId}`);
        
        // Log activity event for refinement start
        await ActivityEvent.create({
          type: 'agent_refinement_started',
          entityType: 'process_improvement',
          entityId: improvementId,
          details: {
            title: improvement.title,
            confidence: assessment.confidence,
            reasoning: assessment.reasoning,
            agentRole: 'Requirements Agent'
          },
          timestamp: new Date()
        });

        try {
          // Refine the improvement with timeout protection
          // Add additional timeout wrapper to ensure we don't get stuck
          const refinementPromise = processImprovementAgentAssessment.refineImprovement(improvement, assessment);
          const maxRefinementTime = 90000; // 90 seconds max (refinement has 60s timeout, but add buffer)
          
          const timeoutWrapper = new Promise<never>((_, reject) => {
            setTimeout(() => {
              reject(new Error(`Refinement exceeded maximum time limit of ${maxRefinementTime}ms`));
            }, maxRefinementTime);
          });
          
          const refined = await Promise.race([refinementPromise, timeoutWrapper]);

          // Apply refinements
          if (refined.title) improvement.title = refined.title;
          if (refined.description) improvement.description = refined.description;
          if (refined.content) improvement.content = refined.content;
          if (refined.tags) improvement.tags = refined.tags;
          if (refined.keywords) improvement.keywords = refined.keywords;

          // Update assessment with refinement timestamp
          if (improvement.approval.agentAssessment) {
            improvement.approval.agentAssessment.refinedAt = new Date();
          }

          // After refinement, approve it
          improvement.approval.status = 'approved';
          improvement.approval.approvedBy = 'agent';
          improvement.approval.approvedAt = new Date();
          if (improvement.status === 'draft') {
            improvement.status = 'active';
          }

          // Add to improvement history
          improvement.improvementHistory.push({
            version: improvement.version + 1,
            changedBy: 'agent',
            changeDate: new Date(),
            changeReason: 'Agent refinement and approval',
            changes: 'Refined by agent based on assessment feedback'
          });
          improvement.version += 1;

          logger.info(`Agent refined and approved improvement: ${improvementId}`);
          
          // Log activity event for successful refinement
          await ActivityEvent.create({
            type: 'agent_refinement_completed',
            entityType: 'process_improvement',
            entityId: improvementId,
            details: {
              title: improvement.title,
              decision: 'refined_and_approved',
              confidence: assessment.confidence,
              durationMs: Date.now() - startTime,
              agentRole: 'Requirements Agent',
              refinedFields: Object.keys(refined).filter(k => (refined as any)[k])
            },
            timestamp: new Date()
          });
        } catch (refinementError: any) {
          // Refinement failed - still approve with original content
          logger.warn(`Refinement failed for ${improvementId}, approving with original content: ${refinementError.message}`);
          
          improvement.approval.status = 'approved';
          improvement.approval.approvedBy = 'agent';
          improvement.approval.approvedAt = new Date();
          if (improvement.status === 'draft') {
            improvement.status = 'active';
          }
          
          // Add note about failed refinement
          if (improvement.approval.agentAssessment) {
            improvement.approval.agentAssessment.refinementFailed = true;
            improvement.approval.agentAssessment.refinementError = refinementError.message;
          }
          
          logger.info(`Agent approved improvement (refinement skipped): ${improvementId}`);
          
          // Log activity event for failed refinement
          await ActivityEvent.create({
            type: 'agent_assessment_failed',
            entityType: 'process_improvement',
            entityId: improvementId,
            details: {
              title: improvement.title,
              decision: 'approved_without_refinement',
              error: refinementError.message,
              durationMs: Date.now() - startTime,
              agentRole: 'Requirements Agent'
            },
            timestamp: new Date()
          });
        }
      }

      await improvement.save();
      logger.info(`Agent assessment complete for improvement: ${improvementId}`);
    } catch (error: any) {
      logger.error(`Agent assessment failed for improvement ${improvementId}:`, error);
      
      // Log activity event for assessment failure
      await ActivityEvent.create({
        type: 'agent_assessment_failed',
        entityType: 'process_improvement',
        entityId: improvementId,
        details: {
          error: error.message,
          durationMs: Date.now() - startTime,
          agentRole: 'QA/Audit Agent',
          action: 'assessment_failed'
        },
        timestamp: new Date()
      }).catch(e => logger.error('Failed to log activity event:', e));
      
      // On error, mark as pending for manual review
      try {
        const improvement = await ProcessImprovement.findOne({ id: improvementId });
        if (improvement) {
          improvement.approval = {
            ...improvement.approval,
            status: 'pending',
            requiresApproval: true
          };
          await improvement.save();
        }
      } catch (saveError: any) {
        logger.error(`Failed to update improvement status after assessment error:`, saveError);
      }
    }
  }

  /**
   * Clean up stuck improvements that are in agent-assessing or agent-refining status
   * for more than the specified timeout (default 5 minutes)
   */
  async cleanupStuckImprovements(timeoutMinutes: number = 5): Promise<{ cleaned: number; errors: number }> {
    let cleaned = 0;
    let errors = 0;
    
    try {
      const cutoffTime = new Date(Date.now() - timeoutMinutes * 60 * 1000);
      
      // Find stuck improvements
      const stuckImprovements = await ProcessImprovement.find({
        'approval.status': { $in: ['agent-assessing', 'agent-refining'] },
        updatedAt: { $lt: cutoffTime }
      });

      logger.info(`Found ${stuckImprovements.length} stuck improvements older than ${timeoutMinutes} minutes`);

      for (const improvement of stuckImprovements) {
        try {
          const previousStatus = improvement.approval?.status;
          
          // Approve stuck improvements (fail-safe)
          improvement.approval = {
            ...improvement.approval,
            status: 'approved',
            approvedBy: 'system-cleanup',
            approvedAt: new Date(),
            agentAssessment: {
              ...improvement.approval?.agentAssessment,
              decision: 'approve',
              reasoning: `Auto-approved after being stuck in ${previousStatus} status for ${timeoutMinutes}+ minutes`,
              confidence: 50,
              assessedAt: new Date()
            }
          };
          
          if (improvement.status === 'draft') {
            improvement.status = 'active';
          }
          
          await improvement.save();
          cleaned++;
          
          logger.info(`Cleaned up stuck improvement: ${improvement.id} (was ${previousStatus})`);
        } catch (error: any) {
          errors++;
          logger.error(`Failed to clean up stuck improvement ${improvement.id}:`, error);
        }
      }

      logger.info(`Cleanup complete: ${cleaned} cleaned, ${errors} errors`);
      return { cleaned, errors };
    } catch (error: any) {
      logger.error('Failed to cleanup stuck improvements:', error);
      return { cleaned, errors };
    }
  }
}

export const processImprovementService = new ProcessImprovementService();

