/**
 * Process Analytics Service
 * Comprehensive analytics for process improvements
 */

import { ProcessImprovement } from '../models/ProcessImprovement.model.js';
import { KnowledgeBase } from '../models/KnowledgeBase.model.js';
import { logger } from '../utils/logger.js';

export interface ProcessAnalytics {
  overview: {
    totalImprovements: number;
    activeImprovements: number;
    totalKnowledgeBase: number;
    activeKnowledgeBase: number;
    autoGenerated: number;
    pendingApproval: number;
  };
  usage: {
    mostUsed: Array<{ id: string; title: string; timesUsed: number }>;
    leastUsed: Array<{ id: string; title: string; timesUsed: number }>;
    averageUsage: number;
    totalUsage: number;
  };
  quality: {
    averageCompleteness: number;
    averageClarity: number;
    averageUsefulness: number;
    highQuality: number; // > 80
    lowQuality: number; // < 50
  };
  categories: Array<{
    category: string;
    count: number;
    averageSuccessRate: number;
  }>;
  trends: {
    created: Array<{ date: string; count: number }>;
    used: Array<{ date: string; count: number }>;
  };
  recommendations: string[];
}

class ProcessAnalyticsService {
  /**
   * Get comprehensive analytics
   */
  async getAnalytics(timeRange?: { start: Date; end: Date }): Promise<ProcessAnalytics> {
    try {
      const filter: any = {};
      if (timeRange) {
        filter.createdAt = {
          $gte: timeRange.start,
          $lte: timeRange.end
        };
      }

      const [improvements, knowledgeBase] = await Promise.all([
        ProcessImprovement.find(filter).lean(),
        KnowledgeBase.find(filter).lean()
      ]);

      const overview = this.calculateOverview(improvements, knowledgeBase);
      const usage = this.calculateUsage(improvements);
      const quality = this.calculateQuality(improvements);
      const categories = this.calculateCategories(improvements);
      const trends = this.calculateTrends(improvements, timeRange);
      const recommendations = this.generateRecommendations(improvements, knowledgeBase);

      return {
        overview,
        usage,
        quality,
        categories,
        trends,
        recommendations
      };
    } catch (error: any) {
      logger.error('Failed to get analytics:', error);
      throw error;
    }
  }

  /**
   * Calculate overview statistics
   */
  private calculateOverview(improvements: any[], knowledgeBase: any[]): ProcessAnalytics['overview'] {
    return {
      totalImprovements: improvements.length,
      activeImprovements: improvements.filter(i => i.status === 'active').length,
      totalKnowledgeBase: knowledgeBase.length,
      activeKnowledgeBase: knowledgeBase.filter(kb => kb.status === 'active').length,
      autoGenerated: improvements.filter(i => i.autoGenerated).length,
      pendingApproval: improvements.filter(i => i.approval?.status === 'pending').length
    };
  }

  /**
   * Calculate usage statistics
   */
  private calculateUsage(improvements: any[]): ProcessAnalytics['usage'] {
    const withUsage = improvements
      .map(i => ({
        id: i.id,
        title: i.title,
        timesUsed: i.usage?.timesUsed || 0
      }))
      .sort((a, b) => b.timesUsed - a.timesUsed);

    const totalUsage = withUsage.reduce((sum, i) => sum + i.timesUsed, 0);
    const averageUsage = improvements.length > 0 ? totalUsage / improvements.length : 0;

    return {
      mostUsed: withUsage.slice(0, 10),
      leastUsed: withUsage.slice(-10).reverse(),
      averageUsage,
      totalUsage
    };
  }

  /**
   * Calculate quality metrics
   */
  private calculateQuality(improvements: any[]): ProcessAnalytics['quality'] {
    if (improvements.length === 0) {
      return {
        averageCompleteness: 0,
        averageClarity: 0,
        averageUsefulness: 0,
        highQuality: 0,
        lowQuality: 0
      };
    }

    const completeness = improvements.reduce((sum, i) => sum + (i.quality?.completeness || 0), 0) / improvements.length;
    const clarity = improvements.reduce((sum, i) => sum + (i.quality?.clarity || 0), 0) / improvements.length;
    const usefulness = improvements.reduce((sum, i) => sum + (i.quality?.usefulness || 0), 0) / improvements.length;

    const highQuality = improvements.filter(i => {
      const avg = ((i.quality?.completeness || 0) + (i.quality?.clarity || 0) + (i.quality?.usefulness || 0)) / 3;
      return avg > 80;
    }).length;

    const lowQuality = improvements.filter(i => {
      const avg = ((i.quality?.completeness || 0) + (i.quality?.clarity || 0) + (i.quality?.usefulness || 0)) / 3;
      return avg < 50;
    }).length;

    return {
      averageCompleteness: completeness,
      averageClarity: clarity,
      averageUsefulness: usefulness,
      highQuality,
      lowQuality
    };
  }

  /**
   * Calculate category statistics
   */
  private calculateCategories(improvements: any[]): ProcessAnalytics['categories'] {
    const categoryMap = new Map<string, { count: number; totalSuccessRate: number; successCount: number }>();

    improvements.forEach(i => {
      const category = i.category;
      if (!categoryMap.has(category)) {
        categoryMap.set(category, { count: 0, totalSuccessRate: 0, successCount: 0 });
      }
      const data = categoryMap.get(category)!;
      data.count++;
      if (i.usage?.successRate) {
        data.totalSuccessRate += i.usage.successRate;
        data.successCount++;
      }
    });

    return Array.from(categoryMap.entries()).map(([category, data]) => ({
      category,
      count: data.count,
      averageSuccessRate: data.successCount > 0 ? data.totalSuccessRate / data.successCount : 0
    }));
  }

  /**
   * Calculate trends
   */
  private calculateTrends(improvements: any[], timeRange?: { start: Date; end: Date }): ProcessAnalytics['trends'] {
    const createdMap = new Map<string, number>();
    const usedMap = new Map<string, number>();

    improvements.forEach(i => {
      if (i.createdAt) {
        const date = new Date(i.createdAt).toISOString().split('T')[0];
        createdMap.set(date, (createdMap.get(date) || 0) + 1);
      }

      if (i.usage?.lastUsed) {
        const date = new Date(i.usage.lastUsed).toISOString().split('T')[0];
        usedMap.set(date, (usedMap.get(date) || 0) + (i.usage.timesUsed || 0));
      }
    });

    return {
      created: Array.from(createdMap.entries())
        .map(([date, count]) => ({ date, count }))
        .sort((a, b) => a.date.localeCompare(b.date)),
      used: Array.from(usedMap.entries())
        .map(([date, count]) => ({ date, count }))
        .sort((a, b) => a.date.localeCompare(b.date))
    };
  }

  /**
   * Generate recommendations
   */
  private generateRecommendations(improvements: any[], knowledgeBase: any[]): string[] {
    const recommendations: string[] = [];

    // Low usage items
    const lowUsage = improvements.filter(i => (i.usage?.timesUsed || 0) < 2);
    if (lowUsage.length > 0) {
      recommendations.push(`${lowUsage.length} improvements have low usage. Consider reviewing and updating them.`);
    }

    // Pending approvals
    const pending = improvements.filter(i => i.approval?.status === 'pending');
    if (pending.length > 0) {
      recommendations.push(`${pending.length} improvements are pending approval. Review and approve or reject them.`);
    }

    // Low quality items
    const lowQuality = improvements.filter(i => {
      const avg = ((i.quality?.completeness || 0) + (i.quality?.clarity || 0) + (i.quality?.usefulness || 0)) / 3;
      return avg < 50;
    });
    if (lowQuality.length > 0) {
      recommendations.push(`${lowQuality.length} improvements have low quality scores. Consider improving them.`);
    }

    // Unused knowledge base entries
    const unusedKB = knowledgeBase.filter(kb => (kb.usage?.views || 0) === 0);
    if (unusedKB.length > 0) {
      recommendations.push(`${unusedKB.length} knowledge base entries have never been viewed. Consider promoting or updating them.`);
    }

    return recommendations;
  }

  /**
   * Get ROI for an improvement
   */
  async calculateROI(improvementId: string): Promise<{
    timesUsed: number;
    averageSuccessRate: number;
    estimatedTimeSaved: number; // in hours
    estimatedValue: number; // in dollars
  }> {
    try {
      const improvement = await ProcessImprovement.findOne({ id: improvementId });
      if (!improvement) {
        throw new Error('Improvement not found');
      }

      const timesUsed = improvement.usage?.timesUsed || 0;
      const successRate = improvement.usage?.successRate || 0;
      
      // Estimate time saved per use (assuming 1 hour saved per successful use)
      const averageTimeSavedPerUse = 1; // hours
      const estimatedTimeSaved = timesUsed * (successRate / 100) * averageTimeSavedPerUse;
      
      // Estimate value (assuming $50/hour developer time)
      const hourlyRate = 50;
      const estimatedValue = estimatedTimeSaved * hourlyRate;

      return {
        timesUsed,
        averageSuccessRate: successRate,
        estimatedTimeSaved,
        estimatedValue
      };
    } catch (error: any) {
      logger.error('Failed to calculate ROI:', error);
      throw error;
    }
  }
}

export const processAnalyticsService = new ProcessAnalyticsService();
















