import React, { useState, useEffect, useMemo } from 'react';
import { 
  Database, 
  FileText, 
  Code, 
  TestTube, 
  Shield, 
  Settings, 
  Search, 
  Filter, 
  Eye, 
  Download, 
  Trash2, 
  RefreshCw, 
  ChevronDown, 
  ChevronRight,
  BookOpen,
  Layers,
  Clock,
  Tag,
  FolderOpen,
  FileCode,
  AlertTriangle,
  CheckCircle,
  Archive,
  Plus,
  Edit,
  X,
  Bot,
  Workflow,
  Lightbulb
} from 'lucide-react';

interface KnowledgeBaseEntry {
  _id: string;
  id: string;
  name: string;
  description: string;
  category: 'process' | 'technical' | 'quality' | 'security' | 'compliance' | 'best-practices' | 'troubleshooting' | 'general';
  content: string;
  status: 'draft' | 'active' | 'deprecated' | 'archived';
  priority: 'low' | 'medium' | 'high' | 'critical';
  version: number;
  tags: string[];
  keywords: string[];
  autoGenerated: boolean;
  source?: {
    type: 'agent-learning' | 'user-created' | 'imported' | 'system-generated' | 'aggregated';
    agentRole?: string;
    taskId?: string;
    projectId?: string;
  };
  applicableTo?: {
    agentRoles?: string[];
    projectTypes?: string[];
    methodologies?: string[];
  };
  usage: {
    views: number;
    timesReferenced: number;
    helpfulCount: number;
    notHelpfulCount: number;
  };
  quality: {
    completeness: number;
    accuracy: number;
    clarity: number;
    usefulness: number;
  };
  createdAt: string;
  updatedAt: string;
}

interface ProjectArtifact {
  id: string;
  title: string;
  type: string;
  phase: string;
  content: string;
  createdBy: string;
  timestamp: number;
  tags: string[];
  projectId: string;
  projectName: string;
}

interface KnowledgeBaseManagerProps {
  token?: string;
}

const KnowledgeBaseManager: React.FC<KnowledgeBaseManagerProps> = ({ token }) => {
  const [activeView, setActiveView] = useState<'knowledge-base' | 'project-artifacts'>('knowledge-base');
  const [knowledgeEntries, setKnowledgeEntries] = useState<KnowledgeBaseEntry[]>([]);
  const [projectArtifacts, setProjectArtifacts] = useState<ProjectArtifact[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [selectedStatus, setSelectedStatus] = useState<string>('all');
  const [selectedType, setSelectedType] = useState<string>('all');
  const [expandedEntry, setExpandedEntry] = useState<string | null>(null);
  const [viewingEntry, setViewingEntry] = useState<KnowledgeBaseEntry | null>(null);
  const [viewingArtifact, setViewingArtifact] = useState<ProjectArtifact | null>(null);

  // Fetch knowledge base entries
  const fetchKnowledgeBase = async () => {
    setLoading(true);
    setError(null);
    try {
      const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:3002';
      const response = await fetch(`${apiBase}/api/admin/process-improvements/knowledge-base?limit=100`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch knowledge base entries');
      }
      
      const data = await response.json();
      setKnowledgeEntries(data.data?.entries || []);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  // Fetch project artifacts
  const fetchProjectArtifacts = async () => {
    setLoading(true);
    setError(null);
    try {
      const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:3002';
      const response = await fetch(`${apiBase}/api/admin/system-artifacts`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (!response.ok) {
        throw new Error('Failed to fetch project artifacts');
      }
      
      const data = await response.json();
      setProjectArtifacts(data.data?.artifacts || []);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (activeView === 'knowledge-base') {
      fetchKnowledgeBase();
    } else {
      fetchProjectArtifacts();
    }
  }, [activeView, token]);

  // Filter knowledge entries
  const filteredKnowledgeEntries = useMemo(() => {
    return knowledgeEntries.filter(entry => {
      const matchesSearch = !searchQuery || 
        entry.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        entry.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
        entry.tags.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));
      
      const matchesCategory = selectedCategory === 'all' || entry.category === selectedCategory;
      const matchesStatus = selectedStatus === 'all' || entry.status === selectedStatus;
      
      return matchesSearch && matchesCategory && matchesStatus;
    });
  }, [knowledgeEntries, searchQuery, selectedCategory, selectedStatus]);

  // Filter project artifacts
  const filteredArtifacts = useMemo(() => {
    return projectArtifacts.filter(artifact => {
      const matchesSearch = !searchQuery || 
        artifact.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        artifact.projectName?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        artifact.tags?.some(tag => tag.toLowerCase().includes(searchQuery.toLowerCase()));
      
      const matchesType = selectedType === 'all' || artifact.type === selectedType;
      
      return matchesSearch && matchesType;
    });
  }, [projectArtifacts, searchQuery, selectedType]);

  // Get unique artifact types
  const artifactTypes = useMemo(() => {
    const types = new Set(projectArtifacts.map(a => a.type));
    return Array.from(types);
  }, [projectArtifacts]);

  const getCategoryIcon = (category: string) => {
    switch (category) {
      case 'process': return <Workflow size={16} className="text-blue-600" />;
      case 'technical': return <Code size={16} className="text-purple-600" />;
      case 'quality': return <CheckCircle size={16} className="text-emerald-600" />;
      case 'security': return <Shield size={16} className="text-red-600" />;
      case 'compliance': return <FileText size={16} className="text-orange-600" />;
      case 'best-practices': return <Lightbulb size={16} className="text-cyan-600" />;
      case 'troubleshooting': return <AlertTriangle size={16} className="text-amber-600" />;
      default: return <BookOpen size={16} className="text-slate-600" />;
    }
  };

  // Match ProcessImprovementManager color scheme
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active': return 'bg-green-100 text-green-700';
      case 'draft': return 'bg-slate-100 text-slate-700';
      case 'deprecated': return 'bg-yellow-100 text-yellow-700';
      case 'archived': return 'bg-gray-100 text-gray-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-100 text-red-700';
      case 'high': return 'bg-orange-100 text-orange-700';
      case 'medium': return 'bg-blue-100 text-blue-700';
      case 'low': return 'bg-slate-100 text-slate-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  const getArtifactTypeIcon = (type: string) => {
    switch (type) {
      case 'requirement': return <FileText size={16} className="text-blue-600" />;
      case 'design': return <Layers size={16} className="text-purple-600" />;
      case 'code': return <Code size={16} className="text-emerald-600" />;
      case 'test-plan': return <TestTube size={16} className="text-orange-600" />;
      case 'audit-report': return <Shield size={16} className="text-red-600" />;
      case 'defect': return <AlertTriangle size={16} className="text-amber-600" />;
      case 'build': return <Settings size={16} className="text-slate-600" />;
      default: return <FileCode size={16} className="text-slate-600" />;
    }
  };

  const getSourceBadge = (source?: KnowledgeBaseEntry['source']) => {
    if (!source) return null;
    
    const colors: Record<string, string> = {
      'agent-learning': 'bg-purple-100 text-purple-700',
      'user-created': 'bg-blue-100 text-blue-700',
      'imported': 'bg-green-100 text-green-700',
      'system-generated': 'bg-amber-100 text-amber-700',
      'aggregated': 'bg-cyan-100 text-cyan-700'
    };
    
    return (
      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${colors[source.type] || 'bg-slate-100 text-slate-700'}`}>
        {source.type === 'agent-learning' && <Bot size={10} className="inline mr-1" />}
        {source.type.replace('-', ' ')}
      </span>
    );
  };

  const renderKnowledgeBaseView = () => (
    <div className="space-y-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center gap-4 bg-white p-4 rounded-lg border border-slate-200">
        <div className="flex-1 min-w-[200px]">
          <div className="relative">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search knowledge base..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>
        
        <select
          value={selectedCategory}
          onChange={(e) => setSelectedCategory(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">All Categories</option>
          <option value="process">Process</option>
          <option value="technical">Technical</option>
          <option value="quality">Quality</option>
          <option value="security">Security</option>
          <option value="compliance">Compliance</option>
          <option value="best-practices">Best Practices</option>
          <option value="troubleshooting">Troubleshooting</option>
          <option value="general">General</option>
        </select>
        
        <select
          value={selectedStatus}
          onChange={(e) => setSelectedStatus(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">All Status</option>
          <option value="active">Active</option>
          <option value="draft">Draft</option>
          <option value="deprecated">Deprecated</option>
          <option value="archived">Archived</option>
        </select>
        
        <button
          onClick={fetchKnowledgeBase}
          className="px-3 py-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
        >
          <RefreshCw size={16} />
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-blue-600">
              <Database size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Total Entries</p>
          <h3 className="text-2xl font-bold text-slate-800">{knowledgeEntries.length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-emerald-600">
              <CheckCircle size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Active</p>
          <h3 className="text-2xl font-bold text-slate-800">{knowledgeEntries.filter(e => e.status === 'active').length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-purple-600">
              <Bot size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Auto-Generated</p>
          <h3 className="text-2xl font-bold text-slate-800">{knowledgeEntries.filter(e => e.autoGenerated).length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-cyan-600">
              <Eye size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Total Views</p>
          <h3 className="text-2xl font-bold text-slate-800">{knowledgeEntries.reduce((acc, e) => acc + e.usage.views, 0)}</h3>
        </div>
      </div>

      {/* Entries List */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <RefreshCw size={24} className="animate-spin text-blue-500" />
          <span className="ml-2 text-slate-600">Loading knowledge base...</span>
        </div>
      ) : filteredKnowledgeEntries.length === 0 ? (
        <div className="bg-white rounded-lg border border-slate-200 p-12 text-center">
          <Database size={48} className="mx-auto text-slate-300 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 mb-2">No Knowledge Base Entries</h3>
          <p className="text-sm text-slate-500">
            {searchQuery || selectedCategory !== 'all' || selectedStatus !== 'all'
              ? 'No entries match your filters. Try adjusting your search criteria.'
              : 'Knowledge base entries will appear here as the system learns from agent activities and project work.'}
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {filteredKnowledgeEntries.map(entry => (
            <div
              key={entry._id}
              className="bg-white rounded-lg border border-slate-200 hover:border-blue-300 transition-colors"
            >
              <div
                className="p-4 cursor-pointer"
                onClick={() => setExpandedEntry(expandedEntry === entry.id ? null : entry.id)}
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-start gap-3">
                    <div className="mt-1">
                      {getCategoryIcon(entry.category)}
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h3 className="font-semibold text-slate-800">{entry.name}</h3>
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getStatusColor(entry.status)}`}>
                          {entry.status}
                        </span>
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${getPriorityColor(entry.priority)}`}>
                          {entry.priority}
                        </span>
                        {entry.autoGenerated && (
                          <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                            <Bot size={10} className="inline mr-1" />
                            Auto-Generated
                          </span>
                        )}
                        {getSourceBadge(entry.source)}
                      </div>
                      <p className="text-sm text-slate-600 mt-1 line-clamp-2">{entry.description}</p>
                      <div className="flex items-center gap-4 mt-2 text-xs text-slate-500">
                        <span className="flex items-center gap-1">
                          <Eye size={12} />
                          {entry.usage.views} views
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock size={12} />
                          v{entry.version}
                        </span>
                        {entry.tags.length > 0 && (
                          <span className="flex items-center gap-1">
                            <Tag size={12} />
                            {entry.tags.slice(0, 3).join(', ')}
                            {entry.tags.length > 3 && ` +${entry.tags.length - 3}`}
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setViewingEntry(entry);
                      }}
                      className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                      title="View details"
                    >
                      <Eye size={16} />
                    </button>
                    {expandedEntry === entry.id ? (
                      <ChevronDown size={20} className="text-slate-400" />
                    ) : (
                      <ChevronRight size={20} className="text-slate-400" />
                    )}
                  </div>
                </div>
              </div>

              {/* Expanded Content */}
              {expandedEntry === entry.id && (
                <div className="px-4 pb-4 border-t border-slate-100">
                  <div className="pt-4 prose prose-sm max-w-none">
                    <pre className="bg-slate-50 p-4 rounded-lg overflow-auto text-sm whitespace-pre-wrap">
                      {entry.content.slice(0, 1000)}
                      {entry.content.length > 1000 && '...'}
                    </pre>
                  </div>
                  
                  {/* Quality Metrics */}
                  <div className="mt-4 grid grid-cols-4 gap-4">
                    <div className="text-center">
                      <div className="text-lg font-semibold text-slate-800">{entry.quality.completeness}%</div>
                      <div className="text-xs text-slate-500">Completeness</div>
                    </div>
                    <div className="text-center">
                      <div className="text-lg font-semibold text-slate-800">{entry.quality.accuracy}%</div>
                      <div className="text-xs text-slate-500">Accuracy</div>
                    </div>
                    <div className="text-center">
                      <div className="text-lg font-semibold text-slate-800">{entry.quality.clarity}%</div>
                      <div className="text-xs text-slate-500">Clarity</div>
                    </div>
                    <div className="text-center">
                      <div className="text-lg font-semibold text-slate-800">{entry.quality.usefulness}%</div>
                      <div className="text-xs text-slate-500">Usefulness</div>
                    </div>
                  </div>

                  {/* Applicable To */}
                  {entry.applicableTo && (
                    <div className="mt-4">
                      <h4 className="text-xs font-semibold text-slate-600 uppercase mb-2">Applicable To</h4>
                      <div className="flex flex-wrap gap-2">
                        {entry.applicableTo.agentRoles?.map(role => (
                          <span key={role} className="px-2 py-1 bg-blue-50 text-blue-700 rounded text-xs">
                            {role}
                          </span>
                        ))}
                        {entry.applicableTo.methodologies?.map(method => (
                          <span key={method} className="px-2 py-1 bg-green-50 text-green-700 rounded text-xs">
                            {method}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );

  const renderProjectArtifactsView = () => (
    <div className="space-y-4">
      {/* Filters */}
      <div className="flex flex-wrap items-center gap-4 bg-white p-4 rounded-lg border border-slate-200">
        <div className="flex-1 min-w-[200px]">
          <div className="relative">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              placeholder="Search artifacts..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>
        
        <select
          value={selectedType}
          onChange={(e) => setSelectedType(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="all">All Types</option>
          {artifactTypes.map(type => (
            <option key={type} value={type}>{type}</option>
          ))}
        </select>
        
        <button
          onClick={fetchProjectArtifacts}
          className="px-3 py-2 text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
        >
          <RefreshCw size={16} />
        </button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4">
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-blue-600">
              <Layers size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Total Artifacts</p>
          <h3 className="text-2xl font-bold text-slate-800">{projectArtifacts.length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-cyan-600">
              <FileText size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Requirements</p>
          <h3 className="text-2xl font-bold text-slate-800">{projectArtifacts.filter(a => a.type === 'requirement').length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-emerald-600">
              <Code size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Code Artifacts</p>
          <h3 className="text-2xl font-bold text-slate-800">{projectArtifacts.filter(a => a.type === 'code').length}</h3>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="p-3 rounded-lg bg-purple-600">
              <FolderOpen size={24} className="text-white" />
            </div>
          </div>
          <p className="text-sm text-slate-500 font-medium mb-1">Projects</p>
          <h3 className="text-2xl font-bold text-slate-800">{new Set(projectArtifacts.map(a => a.projectId)).size}</h3>
        </div>
      </div>

      {/* Artifacts List */}
      {loading ? (
        <div className="flex items-center justify-center py-12">
          <RefreshCw size={24} className="animate-spin text-blue-500" />
          <span className="ml-2 text-slate-600">Loading artifacts...</span>
        </div>
      ) : filteredArtifacts.length === 0 ? (
        <div className="bg-white rounded-lg border border-slate-200 p-12 text-center">
          <FolderOpen size={48} className="mx-auto text-slate-300 mb-4" />
          <h3 className="text-lg font-medium text-slate-700 mb-2">No Project Artifacts</h3>
          <p className="text-sm text-slate-500">
            {searchQuery || selectedType !== 'all'
              ? 'No artifacts match your filters. Try adjusting your search criteria.'
              : 'Project artifacts will appear here as agents create them during project work.'}
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredArtifacts.map(artifact => (
            <div
              key={artifact.id}
              className="bg-white rounded-lg border border-slate-200 hover:border-blue-300 transition-colors cursor-pointer"
              onClick={() => setViewingArtifact(artifact)}
            >
              <div className="p-4">
                <div className="flex items-start gap-3">
                  <div className="mt-1">
                    {getArtifactTypeIcon(artifact.type)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-slate-800 truncate">{artifact.title}</h3>
                    <div className="flex items-center gap-2 mt-1">
                      <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                        {artifact.type}
                      </span>
                      <span className="px-2 py-0.5 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                        {artifact.phase}
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 mt-2 truncate">
                      <FolderOpen size={10} className="inline mr-1" />
                      {artifact.projectName || 'Unknown Project'}
                    </p>
                    <div className="flex items-center gap-2 mt-2 text-xs text-slate-500">
                      <span className="flex items-center gap-1">
                        <Bot size={10} />
                        {artifact.createdBy}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock size={10} />
                        {new Date(artifact.timestamp).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  // View Modal for Knowledge Entry
  const renderKnowledgeModal = () => {
    if (!viewingEntry) return null;
    
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-xl shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
          <div className="flex items-center justify-between p-4 border-b border-slate-200">
            <div className="flex items-center gap-3">
              {getCategoryIcon(viewingEntry.category)}
              <h2 className="text-xl font-bold text-slate-800">{viewingEntry.name}</h2>
            </div>
            <button
              onClick={() => setViewingEntry(null)}
              className="p-2 text-slate-400 hover:text-slate-600 rounded-lg transition-colors"
            >
              <X size={20} />
            </button>
          </div>
          
          <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
            <div className="flex flex-wrap gap-2 mb-4">
              <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(viewingEntry.status)}`}>
                {viewingEntry.status}
              </span>
              <span className={`px-2 py-1 rounded-full text-xs font-medium ${getPriorityColor(viewingEntry.priority)}`}>
                {viewingEntry.priority}
              </span>
              <span className="px-2 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                v{viewingEntry.version}
              </span>
              {viewingEntry.autoGenerated && (
                <span className="px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                  <Bot size={10} className="inline mr-1" />
                  Auto-Generated
                </span>
              )}
              {getSourceBadge(viewingEntry.source)}
            </div>
            
            <p className="text-slate-600 mb-6">{viewingEntry.description}</p>
            
            <div className="prose prose-sm max-w-none">
              <pre className="bg-slate-50 p-4 rounded-lg overflow-auto whitespace-pre-wrap text-sm">
                {viewingEntry.content}
              </pre>
            </div>
            
            {viewingEntry.tags.length > 0 && (
              <div className="mt-6">
                <h4 className="text-sm font-semibold text-slate-700 mb-2">Tags</h4>
                <div className="flex flex-wrap gap-2">
                  {viewingEntry.tags.map(tag => (
                    <span key={tag} className="px-2 py-1 bg-slate-100 text-slate-700 rounded text-xs">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            )}
            
            <div className="mt-6 grid grid-cols-4 gap-4">
              <div className="bg-slate-50 p-3 rounded-lg text-center">
                <div className="text-lg font-semibold text-slate-800">{viewingEntry.quality.completeness}%</div>
                <div className="text-xs text-slate-500">Completeness</div>
              </div>
              <div className="bg-slate-50 p-3 rounded-lg text-center">
                <div className="text-lg font-semibold text-slate-800">{viewingEntry.quality.accuracy}%</div>
                <div className="text-xs text-slate-500">Accuracy</div>
              </div>
              <div className="bg-slate-50 p-3 rounded-lg text-center">
                <div className="text-lg font-semibold text-slate-800">{viewingEntry.quality.clarity}%</div>
                <div className="text-xs text-slate-500">Clarity</div>
              </div>
              <div className="bg-slate-50 p-3 rounded-lg text-center">
                <div className="text-lg font-semibold text-slate-800">{viewingEntry.quality.usefulness}%</div>
                <div className="text-xs text-slate-500">Usefulness</div>
              </div>
            </div>
            
            <div className="mt-6 flex items-center justify-between text-xs text-slate-500">
              <span>Created: {new Date(viewingEntry.createdAt).toLocaleString()}</span>
              <span>Updated: {new Date(viewingEntry.updatedAt).toLocaleString()}</span>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // View Modal for Artifact
  const renderArtifactModal = () => {
    if (!viewingArtifact) return null;
    
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-xl shadow-xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
          <div className="flex items-center justify-between p-4 border-b border-slate-200">
            <div className="flex items-center gap-3">
              {getArtifactTypeIcon(viewingArtifact.type)}
              <h2 className="text-xl font-bold text-slate-800">{viewingArtifact.title}</h2>
            </div>
            <button
              onClick={() => setViewingArtifact(null)}
              className="p-2 text-slate-400 hover:text-slate-600 rounded-lg transition-colors"
            >
              <X size={20} />
            </button>
          </div>
          
          <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
            <div className="flex flex-wrap gap-2 mb-4">
              <span className="px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-700">
                {viewingArtifact.type}
              </span>
              <span className="px-2 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-700">
                {viewingArtifact.phase}
              </span>
              <span className="px-2 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700">
                <Bot size={10} className="inline mr-1" />
                {viewingArtifact.createdBy}
              </span>
            </div>
            
            <div className="mb-4 p-3 bg-slate-50 rounded-lg">
              <div className="flex items-center gap-2 text-sm text-slate-600">
                <FolderOpen size={14} />
                <span className="font-medium">Project:</span>
                <span>{viewingArtifact.projectName || 'Unknown Project'}</span>
              </div>
            </div>
            
            <div className="prose prose-sm max-w-none">
              <pre className="bg-slate-50 p-4 rounded-lg overflow-auto whitespace-pre-wrap text-sm">
                {viewingArtifact.content}
              </pre>
            </div>
            
            {viewingArtifact.tags && viewingArtifact.tags.length > 0 && (
              <div className="mt-6">
                <h4 className="text-sm font-semibold text-slate-700 mb-2">Tags</h4>
                <div className="flex flex-wrap gap-2">
                  {viewingArtifact.tags.map(tag => (
                    <span key={tag} className="px-2 py-1 bg-slate-100 text-slate-700 rounded text-xs">
                      {tag}
                    </span>
                  ))}
                </div>
              </div>
            )}
            
            <div className="mt-6 text-xs text-slate-500">
              Created: {new Date(viewingArtifact.timestamp).toLocaleString()}
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 flex items-center gap-2">
            <Database size={28} className="text-blue-600" />
            Knowledge Base
          </h2>
          <p className="text-sm text-slate-500 mt-1">
            View all system-generated knowledge and project artifacts
          </p>
        </div>
      </div>

      {/* View Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200">
        <button
          onClick={() => setActiveView('knowledge-base')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeView === 'knowledge-base'
              ? 'border-b-2 border-blue-600 text-blue-600'
              : 'text-slate-600 hover:text-slate-800'
          }`}
        >
          <BookOpen size={16} className="inline mr-2" />
          Knowledge Base ({knowledgeEntries.length})
        </button>
        <button
          onClick={() => setActiveView('project-artifacts')}
          className={`px-4 py-2 font-medium transition-colors ${
            activeView === 'project-artifacts'
              ? 'border-b-2 border-blue-600 text-blue-600'
              : 'text-slate-600 hover:text-slate-800'
          }`}
        >
          <FileCode size={16} className="inline mr-2" />
          Project Artifacts ({projectArtifacts.length})
        </button>
      </div>

      {/* Error Display */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-center gap-3">
          <AlertTriangle size={20} className="text-red-500" />
          <span className="text-red-700">{error}</span>
        </div>
      )}

      {/* Content */}
      {activeView === 'knowledge-base' ? renderKnowledgeBaseView() : renderProjectArtifactsView()}

      {/* Modals */}
      {renderKnowledgeModal()}
      {renderArtifactModal()}
    </div>
  );
};

export default KnowledgeBaseManager;

