import React, { useState, useEffect } from 'react';
import {
  BarChart3, TrendingUp, TrendingDown, Star, CheckCircle, XCircle,
  Clock, Users, FileText, Zap, AlertCircle, Loader2, Calendar,
  DollarSign, Target, Award
} from 'lucide-react';
import { getProcessAnalytics, calculateROI, ProcessAnalytics } from '../services/processAnalyticsApi';

interface ProcessAnalyticsDashboardProps {
  token: string;
}

const ProcessAnalyticsDashboard: React.FC<ProcessAnalyticsDashboardProps> = ({ token }) => {
  const [analytics, setAnalytics] = useState<ProcessAnalytics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [dateRange, setDateRange] = useState<{ start?: string; end?: string }>({});

  useEffect(() => {
    loadAnalytics();
  }, [token, dateRange]);

  const loadAnalytics = async () => {
    setLoading(true);
    setError(null);
    try {
      const data = await getProcessAnalytics(token, dateRange.start, dateRange.end);
      setAnalytics(data);
    } catch (err: any) {
      setError(err.message || 'Failed to load analytics');
      console.error('Failed to load analytics:', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="animate-spin text-blue-600" size={32} />
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6 text-center">
        <AlertCircle className="mx-auto mb-2 text-red-600" size={32} />
        <p className="text-red-700 font-medium">{error}</p>
      </div>
    );
  }

  if (!analytics) {
    return null;
  }

  const StatCard = ({ icon: Icon, label, value, trend, color }: any) => (
    <div className="bg-white rounded-lg border border-slate-200 p-6">
      <div className="flex items-center justify-between mb-4">
        <div className={`p-3 rounded-lg ${color}`}>
          <Icon size={24} className="text-white" />
        </div>
        {trend && (
          <div className={`flex items-center gap-1 text-sm font-semibold ${
            trend > 0 ? 'text-emerald-600' : trend < 0 ? 'text-red-600' : 'text-slate-600'
          }`}>
            {trend > 0 ? <TrendingUp size={16} /> : trend < 0 ? <TrendingDown size={16} /> : null}
            {trend > 0 ? '+' : ''}{trend}%
          </div>
        )}
      </div>
      <p className="text-sm text-slate-500 font-medium mb-1">{label}</p>
      <h3 className="text-2xl font-bold text-slate-800">{value.toLocaleString()}</h3>
    </div>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Process Analytics Dashboard</h2>
          <p className="text-sm text-slate-500 mt-1">
            Comprehensive insights into process improvements and knowledge base
          </p>
        </div>
        <div className="flex gap-2">
          <input
            type="date"
            value={dateRange.start || ''}
            onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
            className="px-3 py-2 border border-slate-300 rounded-lg text-sm"
            placeholder="Start Date"
          />
          <input
            type="date"
            value={dateRange.end || ''}
            onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
            className="px-3 py-2 border border-slate-300 rounded-lg text-sm"
            placeholder="End Date"
          />
        </div>
      </div>

      {/* Overview Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          icon={FileText}
          label="Total Improvements"
          value={analytics.overview.totalImprovements}
          color="bg-blue-500"
        />
        <StatCard
          icon={CheckCircle}
          label="Active Improvements"
          value={analytics.overview.activeImprovements}
          color="bg-green-500"
        />
        <StatCard
          icon={Users}
          label="Knowledge Base Entries"
          value={analytics.overview.totalKnowledgeBase}
          color="bg-purple-500"
        />
        <StatCard
          icon={Zap}
          label="Auto-Generated"
          value={analytics.overview.autoGenerated}
          color="bg-orange-500"
        />
      </div>

      {/* Usage Statistics */}
      <div className="bg-white rounded-lg border border-slate-200 p-6">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
          <BarChart3 size={20} /> Usage Statistics
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <p className="text-sm text-slate-500 mb-2">Total Usage</p>
            <h4 className="text-2xl font-bold text-slate-800">{analytics.usage.totalUsage}</h4>
            <p className="text-sm text-slate-500 mt-1">Average: {analytics.usage.averageUsage.toFixed(1)} per improvement</p>
          </div>
          <div>
            <p className="text-sm text-slate-500 mb-2">Most Used</p>
            <div className="space-y-2">
              {analytics.usage.mostUsed.slice(0, 5).map((item, idx) => (
                <div key={idx} className="flex items-center justify-between p-2 bg-slate-50 rounded">
                  <span className="text-sm font-medium text-slate-700 truncate flex-1">{item.title}</span>
                  <span className="text-sm font-bold text-blue-600 ml-2">{item.timesUsed}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Quality Metrics */}
      <div className="bg-white rounded-lg border border-slate-200 p-6">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
          <Star size={20} /> Quality Metrics
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <p className="text-sm text-slate-500 mb-2">Average Completeness</p>
            <div className="flex items-center gap-2">
              <div className="flex-1 h-3 bg-slate-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-blue-500 transition-all"
                  style={{ width: `${analytics.quality.averageCompleteness}%` }}
                />
              </div>
              <span className="text-sm font-bold text-slate-700">{analytics.quality.averageCompleteness.toFixed(0)}%</span>
            </div>
          </div>
          <div>
            <p className="text-sm text-slate-500 mb-2">Average Clarity</p>
            <div className="flex items-center gap-2">
              <div className="flex-1 h-3 bg-slate-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-green-500 transition-all"
                  style={{ width: `${analytics.quality.averageClarity}%` }}
                />
              </div>
              <span className="text-sm font-bold text-slate-700">{analytics.quality.averageClarity.toFixed(0)}%</span>
            </div>
          </div>
          <div>
            <p className="text-sm text-slate-500 mb-2">Average Usefulness</p>
            <div className="flex items-center gap-2">
              <div className="flex-1 h-3 bg-slate-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-purple-500 transition-all"
                  style={{ width: `${analytics.quality.averageUsefulness}%` }}
                />
              </div>
              <span className="text-sm font-bold text-slate-700">{analytics.quality.averageUsefulness.toFixed(0)}%</span>
            </div>
          </div>
        </div>
        <div className="mt-4 grid grid-cols-2 gap-4">
          <div className="p-3 bg-green-50 rounded-lg border border-green-200">
            <p className="text-sm text-green-700 font-medium">High Quality (&gt;80%)</p>
            <p className="text-2xl font-bold text-green-800">{analytics.quality.highQuality}</p>
          </div>
          <div className="p-3 bg-red-50 rounded-lg border border-red-200">
            <p className="text-sm text-red-700 font-medium">Low Quality (&lt;50%)</p>
            <p className="text-2xl font-bold text-red-800">{analytics.quality.lowQuality}</p>
          </div>
        </div>
      </div>

      {/* Category Breakdown */}
      <div className="bg-white rounded-lg border border-slate-200 p-6">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
          <Target size={20} /> Category Breakdown
        </h3>
        <div className="space-y-3">
          {analytics.categories.map((cat, idx) => (
            <div key={idx} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg">
              <div className="flex-1">
                <p className="font-semibold text-slate-800">{cat.category}</p>
                <p className="text-sm text-slate-500">{cat.count} improvements</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-bold text-blue-600">{cat.averageSuccessRate.toFixed(1)}%</p>
                <p className="text-xs text-slate-500">Success Rate</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recommendations */}
      {analytics.recommendations.length > 0 && (
        <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-6">
          <h3 className="text-lg font-bold text-yellow-800 mb-4 flex items-center gap-2">
            <AlertCircle size={20} /> Recommendations
          </h3>
          <ul className="space-y-2">
            {analytics.recommendations.map((rec, idx) => (
              <li key={idx} className="flex items-start gap-2 text-yellow-700">
                <span className="text-yellow-600 mt-1">•</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Trends */}
      <div className="bg-white rounded-lg border border-slate-200 p-6">
        <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
          <TrendingUp size={20} /> Trends
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <p className="text-sm text-slate-500 mb-3">Created Over Time</p>
            <div className="space-y-2">
              {analytics.trends.created.slice(-10).map((trend, idx) => (
                <div key={idx} className="flex items-center justify-between text-sm">
                  <span className="text-slate-600">{trend.date}</span>
                  <span className="font-bold text-blue-600">{trend.count}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <p className="text-sm text-slate-500 mb-3">Usage Over Time</p>
            <div className="space-y-2">
              {analytics.trends.used.slice(-10).map((trend, idx) => (
                <div key={idx} className="flex items-center justify-between text-sm">
                  <span className="text-slate-600">{trend.date}</span>
                  <span className="font-bold text-green-600">{trend.count}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProcessAnalyticsDashboard;


