/**
 * Godot 2D Platformer Movement Template
 * GDScript player controller for platformer games
 */

export const GODOT_2D_MOVEMENT_TEMPLATE = `extends KinematicBody2D

# 2D Platformer Player Controller for Godot
# Handles movement, jumping, and basic physics
# Generated by ORBITAI Game Mechanics Service

# Movement settings
export var move_speed = {{MOVE_SPEED}}
export var jump_force = {{JUMP_FORCE}}
export var max_jumps = {{MAX_JUMPS}}
export var gravity = 980

# Ground detection
export var ground_raycast_length = 10

# Internal variables
var velocity = Vector2.ZERO
var jumps_remaining = 0
var is_grounded = false

func _ready():
	jumps_remaining = max_jumps

func _physics_process(delta):
	# Get horizontal input
	var move_input = Input.get_action_strength("ui_right") - Input.get_action_strength("ui_left")
	
	# Apply horizontal movement
	velocity.x = move_input * move_speed
	
	# Apply gravity
	velocity.y += gravity * delta
	
	# Check if grounded
	check_grounded()
	
	# Reset jumps when grounded
	if is_grounded:
		jumps_remaining = max_jumps
	
	# Jump input
	if Input.is_action_just_pressed("ui_up") and jumps_remaining > 0:
		jump()
	
	# Flip sprite based on movement
	if move_input > 0:
		$Sprite.flip_h = false
	elif move_input < 0:
		$Sprite.flip_h = true
	
	# Move the character
	velocity = move_and_slide(velocity, Vector2.UP)

func jump():
	velocity.y = -jump_force
	jumps_remaining -= 1

func check_grounded():
	# Use raycast for ground detection
	var space_state = get_world_2d().direct_space_state
	var result = space_state.intersect_ray(
		global_position,
		global_position + Vector2.DOWN * ground_raycast_length,
		[self]
	)
	is_grounded = result.size() > 0

func _draw():
	# Visualize ground check in editor
	if Engine.editor_hint or OS.is_debug_build():
		var color = Color.green if is_grounded else Color.red
		draw_line(Vector2.ZERO, Vector2.DOWN * ground_raycast_length, color, 2)
`;

export const GODOT_2D_MOVEMENT_CONFIG = {
    id: 'godot-2d-movement',
    name: '2D Platformer Movement (Godot)',
    category: 'movement' as const,
    engine: 'godot' as const,
    language: 'gdscript' as const,
    variables: [
        {
            name: 'MOVE_SPEED',
            type: 'number' as const,
            default: 200,
            description: 'Horizontal movement speed (pixels per second)',
            min: 50,
            max: 500
        },
        {
            name: 'JUMP_FORCE',
            type: 'number' as const,
            default: 400,
            description: 'Upward velocity applied when jumping',
            min: 200,
            max: 800
        },
        {
            name: 'MAX_JUMPS',
            type: 'number' as const,
            default: 1,
            description: 'Maximum number of jumps (1 = single, 2 = double jump)',
            min: 1,
            max: 3
        }
    ],
    dependencies: [],
    instructions: `# Godot 2D Platformer Movement - Setup Instructions

## Prerequisites
- Godot 3.x or 4.x project
- Player scene with KinematicBody2D node
- Ground objects with collision shapes

## Installation Steps

1. **Create Player Scene**
   - Create new scene with KinematicBody2D as root
   - Add Sprite child node for graphics
   - Add CollisionShape2D for player collision

2. **Attach Script**
   - Right-click KinematicBody2D → Attach Script
   - Delete default content
   - Paste the generated GDScript code

3. **Configure Input Map** (Project → Project Settings → Input Map)
   - Add "ui_left" → Left Arrow / A
   - Add "ui_right" → Right Arrow / D
   - Add "ui_up" → Space / W

4. **Adjust Settings** (in Inspector)
   - Move Speed: 200 (normal), 300 (fast)
   - Jump Force: 400 (normal), 500-600 (higher jumps)
   - Max Jumps: 1 (single), 2 (double jump)

5. **Test**
   - Press F5 to run
   - Use Arrow Keys or WASD to move
   - Press Space or W to jump

## Customization Tips
- Lower gravity (e.g., 800) for floatier movement
- Higher move speed (350-400) for faster gameplay
- Enable double jump by setting Max Jumps to 2

## Troubleshooting
- **Falls through ground**: Ensure ground has StaticBody2D with collision
- **Can't jump**: Check Input Map for "ui_up" action
- **Moves too fast/slow**: Adjust move_speed value
- **Slides on ground**: Godot 4 uses move_and_slide() differently - check version
`
};
